# Gradient_Descent - 경사하강법

In [ ]:
import sklearn

print(sklearn.__version__)

1.6.1

In [ ]:
from sklearn.datasets import load_diabetes
import pandas as pd
import numpy as np

diabetes = load_diabetes()
diabetesDF = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
diabetesDF['target'] = diabetes.target
print(diabetesDF.shape)
diabetesDF.head()

(442, 11)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

## 가중치와 편향의 업데이트 값을 계산하는 함수
## **parameter**
- w1 : age 변수(피처)의 weight값
- w2 : sex 변수(피처)의 weight값
- w3 : bmi 변수(피처)의 weight값
- w4 : bp 변수(피처)의 weight값
- bias
- N : input data 건수

In [ ]:
# 기존 강의방식 유지(파라미터가 많아 코드가 길어짐)

def get_update_weights_values(bias, w1, w2, w3, w4, age, sex, bmi, bp, target, learning_rate=0.01):

    N = len(target)  # 타겟 데이터 개수

    # 1. 예측값 계산
    predicted = w1 * age + w2 * sex + w3 * bmi + w4 * bp + bias
    diff = target - predicted

    # 2. 오차 계산
    bias_factors = np.ones((N,))

    # 3. 가중치 및 편향 업데이트량 계산 (기여도/기울기)
    w1_update = -(2/N) * learning_rate * np.dot(age.T, diff)
    w2_update = -(2/N) * learning_rate * np.dot(sex.T, diff)
    w3_update = -(2/N) * learning_rate * np.dot(bmi.T, diff)
    w4_update = -(2/N) * learning_rate * np.dot(bp.T, diff)
    bias_update = -(2/N) * learning_rate * np.dot(bias_factors.T, diff)

    # 4. 손실 함수 (MSE) 계산
    mse_loss = np.mean(np.square(diff))

    # weight와 bias가 update되어야 할 값과 MSE 값을 반환
    return w1_update, w2_update, w3_update, w4_update, bias_update, mse_loss

In [ ]:
'''
# 권장하는 방식(실제 딥러닝 프레임워크 작동방식)

def get_update_weights_value_matrix(bias, weights, X, target, learning_rate=0.01):
    """
    X: (N, 4) 형태의 입력 데이터 Matrix (age, sex, bmi, bp)
    weights: (4,) 형태의 가중치 Vector
    """
    N = len(target)

    # 1. 예측값 계산 (행렬 곱)
    predicted = np.dot(X, weights) + bias

    # 2. 오차 계산
    diff = target - predicted

    # 3. 가중치 및 편향 업데이트량 일괄 계산
    # X.T (4, N) dot diff (N,) -> w_update (4,)
    w_update = -(2/N) * learning_rate * np.dot(X.T, diff)
    bias_update = -(2/N) * learning_rate * np.sum(diff)

    # 4. 손실 함수 (MSE) 계산
    mse_loss = np.mean(np.square(diff))

    return bias_update, w_update, mse_loss
'''

'\n# 권장하는 방식(실제 딥러닝 프레임워크 작동방식)\n\ndef get_update_weights_value_matrix(bias, weights, X, target, learning_rate=0.01):\n    """\n    X: (N, 4) 형태의 입력 데이터 Matrix (age, sex, bmi, bp)\n    weights: (4,) 형태의 가중치 Vector\n    """\n    N = len(target)\n\n    # 1. 예측값 계산 (행렬 곱)\n    predicted = np.dot(X, weights) + bias\n\n    # 2. 오차 계산\n    diff = target - predicted\n\n    # 3. 가중치 및 편향 업데이트량 일괄 계산\n    # X.T (4, N) dot diff (N,) -> w_update (4,)\n    w_update = -(2/N) * learning_rate * np.dot(X.T, diff)\n    bias_update = -(2/N) * learning_rate * np.sum(diff)\n\n    # 4. 손실 함수 (MSE) 계산\n    mse_loss = np.mean(np.square(diff))\n\n    return bias_update, w_update, mse_loss\n'

# Gradient Descent를 적용하는 함수 생성
- iter_epochs 수만큼 반복적으로 get_update_weights_value()를 호출하여, <br>
update될 weihgt/bias값을 구한 뒤
weight/bias를 update 적용

In [ ]:
def gradient_descent(features, target, iter_epochs=1000, verbose=True):

    w1 = np.zeros((1,))
    w2 = np.zeros((1,))
    w3 = np.zeros((1,))
    w4 = np.zeros((1,))
    bias = np.zeros((1,))
    print('최초 w1, w2, w3, w4, bias:', w1, w2, w3, w4, bias)

    learning_rate = 0.01
    age = features[:, 0]
    sex = features[:, 1]
    bmi = features[:, 2]
    bp = features[:, 3]

    for i in range(iter_epochs):

        bias_update, w1_update, w2_update, w3_update, w4_update, mse_loss = get_update_weights_values(bias, w1, w2, w3, w4, age, sex, bmi, bp, target, learning_rate)

        w1 = w1 - w1_update
        w2 = w2 - w2_update
        w3 = w3 - w3_update
        w4 = w4 - w4_update
        bias = bias - bias_update
        if verbose:
            print('Epoch:', i+1, '/', iter_epochs)
            print('w1:', w1, 'w2:', w2, 'w3:', w3, 'w4:', w4, 'bias:', bias)

        return w1, w2, w3, w4, bias

# 학습 팁 & 주의사항

- 학습률(Learning Rate) 조정: 사이킷런의 당뇨병 데이터셋은 피처들이 이미 **정규화(Mean=0, Std=1 내외)** 되어 있어 기본 0.01~0.1 학습률로도 잘 발산하지 않고 실습하기 수월합니다.

- 타겟값 스케일: target 값의 범위가 25-346 정도로 크기 때문에, 초반 **loss(MSE)** 값이 수천~수만 단위로 크게 출력되는 것은 정상입니다.

### Gradient Descent 적용
* 신경망은 데이터를 정규화/표준화 작업을 미리 선행해 주어야 함.
* 이를 위해 사이킷런의 MinMaxScaler를 이용하여 개별 feature값은 0~1사이 값으로 변환후 학습 적용.

In [ ]:
'''
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_features = scaler.fit_transform(bostonDF[['RM', 'LSTAT']])
'''

features = diabetesDF[['age', 'sex', 'bmi', 'bp']].values
target = diabetesDF['target'].values

w1, w2, w3, w4, bias = gradient_descent(features, diabetesDF['target'].values, iter_epochs=5000, verbose=True)
print('##### 최종 w1, w2, w3, w4, bias #######')
print(w1, w2, w3, w4, bias)

최초 w1, w2, w3, w4, bias: [0.] [0.] [0.] [0.] [0.]
Epoch: 1 / 5000
w1: [0.00315454] w2: [0.04296087] w3: [0.0323411] w4: [3.04266968] bias: [0.01376394]
##### 최종 w1, w2, w3, w4, bias #######
[0.00315454] [0.04296087] [0.0323411] [3.04266968] [0.01376394]

### 계산된 Weight와 Bias를 이용하여 Price 예측
* 예측 feature 역시 0~1사이의 scaled값을 이용하고 Weight와 bias를 적용하여 예측값 계산.

In [ ]:
'''
predicted = scaled_features[:, 0]*w1 + scaled_features[:, 1]*w2 + bias
bostonDF['PREDICTED_PRICE'] = predicted
bostonDF.head(10)
'''
predicted = features[:, 0]*w1 + features[:, 1]*w2 + features[:, 2]*w3 + features[:, 3]*w4 + bias
diabetesDF['PREDICTED_TARGET'] = predicted
diabetesDF.head(10)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target,PREDICTED_TARGET
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0,0.084607
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0,-0.069931
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0,0.000395
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0,-0.100342
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0,0.077237
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346,97.0,-0.048918
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357,138.0,-0.034407
7,0.063504,0.050680,-0.001895,0.066629,0.090620,0.108914,0.022869,0.017703,-0.035816,0.003064,63.0,0.218812
8,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014960,0.011349,110.0,-0.103940
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504,310.0,-0.088171

### Keras를 이용하여 모델 학습 및 예측
* Dense Layer를 이용하여 퍼셉트론 구현. units는 1로 설정.

In [ ]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

model = Sequential([
    # 단 하나의 units 설정. input_shape는 2차원, 회귀이므로 activation은 설정하지 않음.
    # weight와 bias 초기화는 kernel_inbitializer와 bias_initializer를 이용.
    Dense(1, input_shape=(4, ), activation=None, kernel_initializer='zeros', bias_initializer='ones')
])
# Adam optimizer를 이용하고 Loss 함수는 Mean Squared Error, 성능 측정 역시 MSE를 이용하여 학습 수행.
model.compile(optimizer=Adam(learning_rate=0.01), loss='mse', metrics=['mse'])
model.fit(features, diabetesDF['target'].values, epochs=1000)

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 28751.0332 - mse: 28751.0332
Epoch 2/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28708.0703 - mse: 28708.0703
Epoch 3/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28664.8027 - mse: 28664.8027
Epoch 4/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28622.1875 - mse: 28622.1875
Epoch 5/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28578.9160 - mse: 28578.9160
Epoch 6/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28536.5703 - mse: 28536.5703
Epoch 7/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28493.4141 - mse: 28493.4141
Epoch 8/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28450.7852 - mse: 28450.7852
Epoch 9/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28408.3965 - mse: 28408.3965
Epoch 10/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28365.7559 - mse: 28365.7559
Epoch 11/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28322.9180 - mse: 28322.9180
Epoch 12/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28281.0449 - mse: 28281.0449
Epoch 13/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28238.2168 - mse: 28238.2168
Epoch 14/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28195.5703 - mse: 28195.5703
Epoch 15/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28153.6328 - mse: 28153.6328
Epoch 16/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28111.5059 - mse: 28111.5059
Epoch 17/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28069.0820 - mse: 28069.0820
Epoch 18/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28026.8984 - mse: 28026.8984
Epoch 19/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27984.9609 - mse: 27984.9609
Epoch 20/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27943.0312 - mse: 27943.0312
Epoch 21/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27900.8027 - mse: 27900.8027
Epoch 22/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27858.6895 - mse: 27858.6895
Epoch 23/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27816.7988 - mse: 27816.7988
Epoch 24/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27775.3027 - mse: 27775.3027
Epoch 25/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27733.4434 - mse: 27733.4434
Epoch 26/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27691.4160 - mse: 27691.4160
Epoch 27/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27650.1680 - mse: 27650.1680
Epoch 28/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27608.3457 - mse: 27608.3457
Epoch 29/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27567.0000 - mse: 27567.0000
Epoch 30/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27525.2480 - mse: 27525.2480
Epoch 31/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27484.3301 - mse: 27484.3301
Epoch 32/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27442.5840 - mse: 27442.5840
Epoch 33/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27401.1738 - mse: 27401.1738
Epoch 34/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27360.0039 - mse: 27360.0039
Epoch 35/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27318.7773 - mse: 27318.7773
Epoch 36/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27277.6680 - mse: 27277.6680
Epoch 37/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27236.4844 - mse: 27236.4844
Epoch 38/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27195.5547 - mse: 27195.5547
Epoch 39/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27154.1914 - mse: 27154.1914
Epoch 40/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27113.6133 - mse: 27113.6133
Epoch 41/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27072.5117 - mse: 27072.5117
Epoch 42/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27031.9570 - mse: 27031.9570
Epoch 43/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26990.8516 - mse: 26990.8516
Epoch 44/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26950.4570 - mse: 26950.4570
Epoch 45/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26909.5176 - mse: 26909.5176
Epoch 46/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26868.7559 - mse: 26868.7559
Epoch 47/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26828.6973 - mse: 26828.6973
Epoch 48/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26787.9707 - mse: 26787.9707
Epoch 49/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26747.4531 - mse: 26747.4531
Epoch 50/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26707.1875 - mse: 26707.1875
Epoch 51/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26666.6680 - mse: 26666.6680
Epoch 52/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26626.5391 - mse: 26626.5391
Epoch 53/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 26586.4863 - mse: 26586.4863
Epoch 54/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 26546.2324 - mse: 26546.2324
Epoch 55/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26505.9043 - mse: 26505.9043
Epoch 56/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 26465.8691 - mse: 26465.8691
Epoch 57/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26426.1172 - mse: 26426.1172
Epoch 58/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26386.2715 - mse: 26386.2715
Epoch 59/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26346.4395 - mse: 26346.4395
Epoch 60/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26306.2871 - mse: 26306.2871
Epoch 61/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26266.6914 - mse: 26266.6914
Epoch 62/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26227.1816 - mse: 26227.1816
Epoch 63/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26187.3477 - mse: 26187.3477
Epoch 64/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26147.5684 - mse: 26147.5684
Epoch 65/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26107.8516 - mse: 26107.8516
Epoch 66/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26068.6465 - mse: 26068.6465
Epoch 67/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 26029.2578 - mse: 26029.2578
Epoch 68/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25989.5430 - mse: 25989.5430
Epoch 69/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25950.4609 - mse: 25950.4609
Epoch 70/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25910.7383 - mse: 25910.7383
Epoch 71/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25871.3379 - mse: 25871.3379
Epoch 72/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25832.3867 - mse: 25832.3867
Epoch 73/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25792.9980 - mse: 25792.9980
Epoch 74/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25754.0137 - mse: 25754.0137
Epoch 75/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25715.2402 - mse: 25715.2402
Epoch 76/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25675.7422 - mse: 25675.7422
Epoch 77/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25637.3164 - mse: 25637.3164
Epoch 78/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25597.4980 - mse: 25597.4980
Epoch 79/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25559.2598 - mse: 25559.2598
Epoch 80/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25520.3672 - mse: 25520.3672
Epoch 81/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25481.4844 - mse: 25481.4844
Epoch 82/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25442.8477 - mse: 25442.8477
Epoch 83/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25404.0371 - mse: 25404.0371
Epoch 84/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25365.1875 - mse: 25365.1875
Epoch 85/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25327.1035 - mse: 25327.1035
Epoch 86/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25288.0117 - mse: 25288.0117
Epoch 87/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25249.7480 - mse: 25249.7480
Epoch 88/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25211.7773 - mse: 25211.7773
Epoch 89/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25172.9551 - mse: 25172.9551
Epoch 90/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25134.5391 - mse: 25134.5391
Epoch 91/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25096.2773 - mse: 25096.2773
Epoch 92/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25058.2852 - mse: 25058.2852
Epoch 93/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25019.9551 - mse: 25019.9551
Epoch 94/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24981.9199 - mse: 24981.9199
Epoch 95/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24943.6406 - mse: 24943.6406
Epoch 96/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24905.7910 - mse: 24905.7910
Epoch 97/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24867.4160 - mse: 24867.4160
Epoch 98/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24829.8320 - mse: 24829.8320
Epoch 99/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24791.6621 - mse: 24791.6621
Epoch 100/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24754.0625 - mse: 24754.0625
Epoch 101/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24716.2324 - mse: 24716.2324
Epoch 102/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24678.1660 - mse: 24678.1660
Epoch 103/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24640.4336 - mse: 24640.4336
Epoch 104/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24603.0527 - mse: 24603.0527
Epoch 105/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24565.2520 - mse: 24565.2520
Epoch 106/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24527.7305 - mse: 24527.7305
Epoch 107/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24489.7012 - mse: 24489.7012
Epoch 108/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24453.0918 - mse: 24453.0918
Epoch 109/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24415.1973 - mse: 24415.1973
Epoch 110/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24377.9727 - mse: 24377.9727
Epoch 111/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24340.4082 - mse: 24340.4082
Epoch 112/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24303.2910 - mse: 24303.2910
Epoch 113/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24266.3887 - mse: 24266.3887
Epoch 114/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24228.4824 - mse: 24228.4824
Epoch 115/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24191.6426 - mse: 24191.6426
Epoch 116/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24154.4590 - mse: 24154.4590
Epoch 117/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24117.7344 - mse: 24117.7344
Epoch 118/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24080.5469 - mse: 24080.5469
Epoch 119/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24043.2715 - mse: 24043.2715
Epoch 120/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24006.3691 - mse: 24006.3691
Epoch 121/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23969.3828 - mse: 23969.3828
Epoch 122/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23933.1738 - mse: 23933.1738
Epoch 123/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23895.7969 - mse: 23895.7969
Epoch 124/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23859.3965 - mse: 23859.3965
Epoch 125/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23822.2246 - mse: 23822.2246
Epoch 126/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23785.5762 - mse: 23785.5762
Epoch 127/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23749.1621 - mse: 23749.1621
Epoch 128/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23712.7129 - mse: 23712.7129
Epoch 129/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23675.9453 - mse: 23675.9453
Epoch 130/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23639.4316 - mse: 23639.4316
Epoch 131/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23603.5098 - mse: 23603.5098
Epoch 132/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23566.4590 - mse: 23566.4590
Epoch 133/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23530.3984 - mse: 23530.3984
Epoch 134/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23494.0059 - mse: 23494.0059
Epoch 135/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23457.6426 - mse: 23457.6426
Epoch 136/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23421.2656 - mse: 23421.2656
Epoch 137/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23385.5059 - mse: 23385.5059
Epoch 138/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23348.9336 - mse: 23348.9336
Epoch 139/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23313.0820 - mse: 23313.0820
Epoch 140/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23276.8965 - mse: 23276.8965
Epoch 141/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23241.3184 - mse: 23241.3184
Epoch 142/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23204.9316 - mse: 23204.9316
Epoch 143/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23168.8047 - mse: 23168.8047
Epoch 144/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23133.8242 - mse: 23133.8242
Epoch 145/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23097.1602 - mse: 23097.1602
Epoch 146/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23062.2578 - mse: 23062.2578
Epoch 147/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23025.8594 - mse: 23025.8594
Epoch 148/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22990.4844 - mse: 22990.4844
Epoch 149/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22954.8105 - mse: 22954.8105
Epoch 150/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22919.0527 - mse: 22919.0527
Epoch 151/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22883.7676 - mse: 22883.7676
Epoch 152/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22848.0977 - mse: 22848.0977
Epoch 153/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22812.9004 - mse: 22812.9004
Epoch 154/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22777.5469 - mse: 22777.5469
Epoch 155/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22741.8555 - mse: 22741.8555
Epoch 156/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22706.5723 - mse: 22706.5723
Epoch 157/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22671.4180 - mse: 22671.4180
Epoch 158/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22635.9141 - mse: 22635.9141
Epoch 159/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22600.8809 - mse: 22600.8809
Epoch 160/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22565.7676 - mse: 22565.7676
Epoch 161/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22530.3535 - mse: 22530.3535
Epoch 162/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22495.3984 - mse: 22495.3984
Epoch 163/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22460.3047 - mse: 22460.3047
Epoch 164/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22425.4629 - mse: 22425.4629
Epoch 165/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22390.1738 - mse: 22390.1738
Epoch 166/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22355.7949 - mse: 22355.7949
Epoch 167/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22320.9824 - mse: 22320.9824
Epoch 168/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22285.9512 - mse: 22285.9512
Epoch 169/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22251.0703 - mse: 22251.0703
Epoch 170/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22216.5996 - mse: 22216.5996
Epoch 171/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22181.8770 - mse: 22181.8770
Epoch 172/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22147.2109 - mse: 22147.2109
Epoch 173/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22112.7344 - mse: 22112.7344
Epoch 174/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22078.1387 - mse: 22078.1387
Epoch 175/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22043.4824 - mse: 22043.4824
Epoch 176/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22008.9297 - mse: 22008.9297
Epoch 177/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21974.7051 - mse: 21974.7051
Epoch 178/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21940.3770 - mse: 21940.3770
Epoch 179/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21905.8145 - mse: 21905.8145
Epoch 180/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21871.5195 - mse: 21871.5195
Epoch 181/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21837.1973 - mse: 21837.1973
Epoch 182/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21803.1953 - mse: 21803.1953
Epoch 183/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21768.5371 - mse: 21768.5371
Epoch 184/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21734.8281 - mse: 21734.8281
Epoch 185/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21700.6699 - mse: 21700.6699
Epoch 186/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21666.2266 - mse: 21666.2266
Epoch 187/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21632.4531 - mse: 21632.4531
Epoch 188/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21598.5059 - mse: 21598.5059
Epoch 189/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21564.1406 - mse: 21564.1406
Epoch 190/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21530.8203 - mse: 21530.8203
Epoch 191/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21496.7148 - mse: 21496.7148
Epoch 192/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21462.8691 - mse: 21462.8691
Epoch 193/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21429.1445 - mse: 21429.1445
Epoch 194/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21395.6270 - mse: 21395.6270
Epoch 195/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21361.4844 - mse: 21361.4844
Epoch 196/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21327.9824 - mse: 21327.9824
Epoch 197/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21294.3398 - mse: 21294.3398
Epoch 198/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21260.7129 - mse: 21260.7129
Epoch 199/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21227.3730 - mse: 21227.3730
Epoch 200/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21194.0996 - mse: 21194.0996
Epoch 201/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21160.5312 - mse: 21160.5312
Epoch 202/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21126.8457 - mse: 21126.8457
Epoch 203/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21093.3555 - mse: 21093.3555
Epoch 204/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21060.3262 - mse: 21060.3262
Epoch 205/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21027.1953 - mse: 21027.1953
Epoch 206/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20993.6328 - mse: 20993.6328
Epoch 207/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20960.5273 - mse: 20960.5273
Epoch 208/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20927.5254 - mse: 20927.5254
Epoch 209/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20894.3379 - mse: 20894.3379
Epoch 210/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20861.1113 - mse: 20861.1113
Epoch 211/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20827.9980 - mse: 20827.9980
Epoch 212/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20795.1699 - mse: 20795.1699
Epoch 213/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20762.3340 - mse: 20762.3340
Epoch 214/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20729.2305 - mse: 20729.2305
Epoch 215/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20696.1406 - mse: 20696.1406
Epoch 216/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20663.4004 - mse: 20663.4004
Epoch 217/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20630.5547 - mse: 20630.5547
Epoch 218/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20597.7441 - mse: 20597.7441
Epoch 219/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20565.0762 - mse: 20565.0762
Epoch 220/1000
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20532.4199 - mse: 20532.4199
Epoch 221/1000

### Keras로 학습된 모델을 이용하여 예측 수행.

In [ ]:
predicted = model.predict(features)
diabetesDF['KERAS_PREDICTED_PRICE'] = predicted
diabetesDF.head(10)

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target,PREDICTED_TARGET,KERAS_PREDICTED_PRICE
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0,0.084607,137.598053
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0,-0.069931,114.894592
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0,0.000395,135.739395
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0,-0.100342,112.496986
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0,0.077237,122.541206
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346,97.0,-0.048918,110.688210
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357,138.0,-0.034407,114.666969
7,0.063504,0.050680,-0.001895,0.066629,0.090620,0.108914,0.022869,0.017703,-0.035816,0.003064,63.0,0.218812,136.735916
8,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014960,0.011349,110.0,-0.103940,130.972580
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504,310.0,-0.088171,120.167702

# Stochastic Gradient Descent와 Mini Batch Gradient Descent 구현
* SGD 는 전체 데이터에서 한건만 임의로 선택하여 Gradient Descent 로 Weight/Bias Update 계산한 뒤 Weight/Bias 적용
* Mini Batch GD는 전체 데이터에서 Batch 건수만큼 데이터를 선택하여 Gradient Descent로 Weight/Bias Update 계산한 뒤 Weight/Bias 적용

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes

diabetes = load_diabetes()
diabetesDF = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
diabetesDF['target'] = diabetes.target
print(diabetesDF.shape)
diabetesDF.head()

(442, 11)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

# SGD 기반으로 Weight/Bias update 값 구하기

In [ ]:
def get_update_weights_values_sgd(bias, w1, w2, w3, w4, age_sgd, sex_sgd, bmi_sgd, bp_sgd, target_sgd, learning_rate=0.01):

    # 타겟 데이터 개수
    N = target_sgd.shape[0]

    predicted_sgd = w1 * age_sgd + w2 * sex_sgd + w3 * bmi_sgd + w4 * bp_sgd + bias

    diff_sgd = target_sgd - predicted_sgd

    bias_factors = np.ones((N,))

    w1_update = -(2/N) * learning_rate * np.dot(age_sgd.T, diff_sgd)
    w2_update = -(2/N) * learning_rate * np.dot(sex_sgd.T, diff_sgd)
    w3_update = -(2/N) * learning_rate * np.dot(bmi_sgd.T, diff_sgd)
    w4_update = -(2/N) * learning_rate * np.dot(bp_sgd.T, diff_sgd)
    bias_update = -(2/N) * learning_rate * np.dot(bias_factors.T, diff_sgd)

    # Mean Squared Error값을 계산
    # mse_loss = np.mean(np.square(diff_sgd))

    # weight와 bias가 update 되어야 할 값들을 반환
    return bias_update, w1_update, w2_update, w3_update, w4_update

# SGD 수행하기(Stochastic Gradient Boosting)

In [ ]:
print(diabetesDF['target'].values.shape)
print(np.random.choice(diabetesDF['target'].values.shape[0], 1))
print(np.random.choice(506, 1))

(442,)
[413]
[213]

In [ ]:
def stoch_gradient_descent(features, target, iter_epochs=1000, verbose=True):
    np.random.seed = 2026
    w1 = np.zeros((1,))
    w2 = np.zeros((1,))
    w3 = np.zeros((1,))
    w4 = np.zeros((1,))
    bias = np.zeros((1,))
    print('initial w1, w2, w3, w4, bias:', w1, w2, w3, w4, bias)

    # learning_rate와 features(age, sex, bmi, bp) 지정.
    learning_rate = 0.01
    age = features[:, 0]
    sex = features[:, 1]
    bmi = features[:, 2]
    bp = features[:, 3]


    for i in range(iter_epochs):
        # iteration 시마다 stoch_gradient_descent를 수행할 데이터를 한개만 추출,
        stochastic_idx = np.random.choice(target.shape[0], 1)
        age_sgd = age[stochastic_idx]
        sex_sgd = sex[stochastic_idx]
        bmi_sgd = bmi[stochastic_idx]
        bp_sgd = bp[stochastic_idx]
        target_sgd = target[stochastic_idx]

        # SGD로 구한 weight/biasd의 update 구하기.
        bias_update, w1_update, w2_update, w3_update, w4_update = get_update_weights_values_sgd(bias, w1, w2, w3, w4, age_sgd, sex_sgd, bmi_sgd, bp_sgd, target_sgd, learning_rate)

        # SGD로 구한 weight/biasd의 update 적용.
        w1 = w1 - w1_update
        w2 = w2 - w2_update
        w3 = w3 - w3_update
        w4 = w4 - w4_update
        bias = bias - bias_update

        if verbose:
            print('Epoch:', i+1, '/', iter_epochs)
            # Loss (전체 학습 data 기반)
            predicted = w1 * age + w2 * sex + w3 * bmi + w4 * bp + bias
            diff = target - predicted
            mse_loss = np.mean(np.square(diff))
            print('w1:', w1, 'w2:', w2, 'w3:', w3, 'w4:', w4, 'bias:', bias)

    return w1, w2, w3, w4, bias

In [ ]:
'''
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_features = scaler.fit_transform(bostonDF[['RM', 'LSTAT']])

w1, w2, bias = st_gradient_descent(scaled_features, bostonDF['PRICE'].values, iter_epochs=5000, verbose=True)
print('##### 최종 w1, w2, bias #######')
print(w1, w2, bias)
'''
features = diabetesDF[['age', 'sex', 'bmi', 'bp']].values
target = diabetesDF['target'].values

w1, w2, w3, w4, bias = stoch_gradient_descent(features, diabetesDF['target'].values, iter_epochs=5000, verbose=True)
print('##### 최종 w1, w2, w3, w4, bias #######')
print(w1, w2, w3, w4, bias)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
Epoch: 2502 / 5000
w1: [27.24134929] w2: [4.11691101] w3: [100.23798206] w4: [73.77533872] bias: [161.54194491]
Epoch: 2503 / 5000
w1: [27.23871468] w2: [4.1387598] w3: [100.25578969] w4: [73.7646338] bias: [161.0525186]
Epoch: 2504 / 5000
w1: [27.25886455] w2: [4.16025895] w3: [100.27954116] w4: [73.78228715] bias: [160.5709244]
Epoch: 2505 / 5000
w1: [27.25091713] w2: [4.16789632] w3: [100.27681928] w4: [73.79440336] bias: [160.72162196]
Epoch: 2506 / 5000
w1: [27.25373636] w2: [4.23476877] w3: [100.37653021] w4: [73.7925829] bias: [159.22363825]
Epoch: 2507 / 5000
w1: [27.41176462] w2: [4.35406192] w3: [100.36192236] w4: [73.94131436] bias: [161.57748346]
Epoch: 2508 / 5000
w1: [27.36539908] w2: [4.32651396] w3: [100.33776021] w4: [73.94439661] bias: [161.03391802]
Epoch: 2509 / 5000
w1: [27.33153773] w2: [4.35738015] w3: [100.29584735] w4: [73.96021957] bias: [160.34249651]
Epoch: 2510 / 5000
w1: [27.31928316] w2: [4.28849253] w3: [100.34969881] w4: [73.92112976] bias: [158.98323331]
Epoch: 2511 / 5000
w1: [27.1888839] w2: [4.18442532] w3: [100.35358943] w4: [73.784312] bias: [156.9298205]
Epoch: 2512 / 5000
w1: [27.10645776] w2: [4.12660136] w3: [100.31064886] w4: [73.74129116] bias: [158.22511272]
Epoch: 2513 / 5000
w1: [27.20691169] w2: [4.06323401] w3: [100.30336963] w4: [73.73324218] bias: [159.64458006]
Epoch: 2514 / 5000
w1: [27.3172662] w2: [4.11638014] w3: [100.40057777] w4: [73.80147387] bias: [158.45407416]
Epoch: 2515 / 5000
w1: [27.35113458] w2: [4.18927878] w3: [100.48932203] w4: [73.89072768] bias: [159.89248119]
Epoch: 2516 / 5000
w1: [27.38987603] w2: [4.16527545] w3: [100.46928981] w4: [73.8999358] bias: [159.41885691]
Epoch: 2517 / 5000
w1: [27.48939683] w2: [4.26826428] w3: [100.62094793] w4: [74.03533582] bias: [161.45099166]
Epoch: 2518 / 5000
w1: [27.42138199] w2: [4.19569501] w3: [100.82987044] w4: [74.1380517] bias: [163.07658774]
Epoch: 2519 / 5000
w1: [27.50345097] w2: [4.11682776] w3: [100.76908281] w4: [74.20045275] bias: [161.52041045]
Epoch: 2520 / 5000
w1: [27.55035358] w2: [4.07064859] w3: [100.7492839] w4: [74.22307846] bias: [162.55485219]
Epoch: 2521 / 5000
w1: [27.54248806] w2: [4.08204489] w3: [100.75444511] w4: [74.22452603] bias: [162.29956809]
Epoch: 2522 / 5000
w1: [27.58818349] w2: [4.12072545] w3: [100.80278132] w4: [74.25628736] bias: [161.43309975]
Epoch: 2523 / 5000
w1: [27.55285663] w2: [4.19992154] w3: [100.9055709] w4: [74.35796329] bias: [159.65905892]
Epoch: 2524 / 5000
w1: [27.51238225] w2: [4.0898299] w3: [101.03911506] w4: [74.53077001] bias: [162.12517913]
Epoch: 2525 / 5000
w1: [27.46848794] w2: [4.01807856] w3: [101.16772754] w4: [74.68949032] bias: [163.7324531]
Epoch: 2526 / 5000
w1: [27.49144768] w2: [3.9043911] w3: [101.13545405] w4: [74.76272764] bias: [166.27912169]
Epoch: 2527 / 5000
w1: [27.57153766] w2: [3.98984409] w3: [101.26286971] w4: [74.85266558] bias: [164.36492248]
Epoch: 2528 / 5000
w1: [27.56047448] w2: [4.04462452] w3: [101.28767893] w4: [74.91877069] bias: [163.13780724]
Epoch: 2529 / 5000
w1: [27.58877323] w2: [4.05640624] w3: [101.30809073] w4: [74.925719] bias: [162.8738895]
Epoch: 2530 / 5000
w1: [27.58521357] w2: [3.97197086] w3: [101.37178017] w4: [75.16244321] bias: [164.76529379]
Epoch: 2531 / 5000
w1: [27.67264799] w2: [3.91950919] w3: [101.4126185] w4: [75.27311194] bias: [165.94046715]
Epoch: 2532 / 5000
w1: [27.62601101] w2: [3.95052004] w3: [101.439391] w4: [75.29140067] bias: [165.24580512]
Epoch: 2533 / 5000
w1: [27.63615558] w2: [3.95516326] w3: [101.43635374] w4: [75.28930402] bias: [165.33742329]
Epoch: 2534 / 5000
w1: [27.68019375] w2: [4.01869876] w3: [101.37002131] w4: [75.26797446] bias: [163.91418937]
Epoch: 2535 / 5000
w1: [27.79773676] w2: [3.90574142] w3: [101.46072561] w4: [75.41873636] bias: [161.68536003]
Epoch: 2536 / 5000
w1: [27.73876797] w2: [3.79578067] w3: [101.53733102] w4: [75.34886992] bias: [159.51565822]
Epoch: 2537 / 5000
w1: [27.74123302] w2: [3.72940041] w3: [101.51863708] w4: [75.44648515] bias: [158.20586913]
Epoch: 2538 / 5000
w1: [27.74395522] w2: [3.79397135] w3: [101.61491634] w4: [75.44472734] bias: [156.75944047]
Epoch: 2539 / 5000
w1: [27.87541631] w2: [3.71598431] w3: [101.67753963] w4: [75.49583617] bias: [155.22063118]
Epoch: 2540 / 5000
w1: [27.89579785] w2: [3.77943002] w3: [101.69540713] w4: [75.49735756] bias: [156.47251664]
Epoch: 2541 / 5000
w1: [27.95444373] w2: [3.87589544] w3: [101.80873772] w4: [75.60452167] bias: [158.37593416]
Epoch: 2542 / 5000
w1: [27.95705844] w2: [3.93791677] w3: [101.8982205] w4: [75.58848364] bias: [156.98661845]
Epoch: 2543 / 5000
w1: [28.03737175] w2: [4.00590092] w3: [101.92893264] w4: [75.65477097] bias: [158.32805465]
Epoch: 2544 / 5000
w1: [28.03763957] w2: [4.01225346] w3: [101.93272985] w4: [75.64773914] bias: [158.1857538]
Epoch: 2545 / 5000
w1: [28.11552711] w2: [4.10689496] w3: [101.86075857] w4: [75.74644776] bias: [160.05318233]
Epoch: 2546 / 5000
w1: [28.10396687] w2: [4.0820126] w3: [101.87915149] w4: [75.76951576] bias: [159.56221347]
Epoch: 2547 / 5000
w1: [28.11539656] w2: [4.0923126] w3: [101.88358551] w4: [75.7809581] bias: [159.765449]
Epoch: 2548 / 5000
w1: [28.16244415] w2: [4.13508382] w3: [101.94529473] w4: [75.87875176] bias: [158.8073475]
Epoch: 2549 / 5000
w1: [28.07698149] w2: [4.20292321] w3: [102.04972323] w4: [75.98326966] bias: [157.28770344]
Epoch: 2550 / 5000
w1: [28.08732582] w2: [4.25340786] w3: [102.06771142] w4: [75.90402581] bias: [156.15681648]
Epoch: 2551 / 5000
w1: [28.06107813] w2: [4.32537908] w3: [102.16981199] w4: [75.99642609] bias: [154.54461711]
Epoch: 2552 / 5000
w1: [28.03620633] w2: [4.30994426] w3: [102.17071728] w4: [76.0065413] bias: [154.24006339]
Epoch: 2553 / 5000
w1: [27.97395613] w2: [4.22708746] w3: [102.20024662] w4: [75.89760899] bias: [152.60516591]
Epoch: 2554 / 5000
w1: [27.97284232] w2: [4.22614464] w3: [102.19925926] w4: [75.89662564] bias: [152.58656245]
Epoch: 2555 / 5000
w1: [27.93925562] w2: [4.2049971] w3: [102.17181162] w4: [75.8580588] bias: [153.06028014]
Epoch: 2556 / 5000
w1: [28.01737992] w2: [4.15571551] w3: [102.24824926] w4: [75.89995379] bias: [154.164218]
Epoch: 2557 / 5000
w1: [28.04679986] w2: [4.24729684] w3: [102.25261606] w4: [75.88970708] bias: [155.97126451]
Epoch: 2558 / 5000
w1: [28.01901417] w2: [4.17658089] w3: [102.27029895] w4: [75.79193245] bias: [154.57592538]
Epoch: 2559 / 5000
w1: [28.05018192] w2: [4.20296397] w3: [102.30708982] w4: [75.80749195] bias: [153.98492821]
Epoch: 2560 / 5000
w1: [28.04741086] w2: [4.20061831] w3: [102.30463337] w4: [75.80504548] bias: [153.93864454]
Epoch: 2561 / 5000
w1: [27.97682597] w2: [4.11485028] w3: [102.37897684] w4: [75.69811224] bias: [152.24630393]
Epoch: 2562 / 5000
w1: [27.92386943] w2: [4.16312262] w3: [102.42414804] w4: [75.58511239] bias: [151.16497405]
Epoch: 2563 / 5000
w1: [27.94556041] w2: [4.23064447] w3: [102.44316347] w4: [75.58673153] bias: [152.49728837]
Epoch: 2564 / 5000
w1: [27.96087319] w2: [4.25951553] w3: [102.42347724] w4: [75.59039876] bias: [151.85055882]
Epoch: 2565 / 5000
w1: [27.91260251] w2: [4.33880243] w3: [102.41152818] w4: [75.52709272] bias: [150.07448386]
Epoch: 2566 / 5000
w1: [27.90958158] w2: [4.32405904] w3: [102.42407293] w4: [75.5138496] bias: [150.40474482]
Epoch: 2567 / 5000
w1: [27.94160328] w2: [4.3844335] w3: [102.34354875] w4: [75.5680804] bias: [149.05231974]
Epoch: 2568 / 5000
w1: [28.1466991] w2: [4.55804438] w3: [102.60658703] w4: [75.65480081] bias: [152.47794072]
Epoch: 2569 / 5000
w1: [28.18278993] w2: [4.61011396] w3: [102.55222526] w4: [75.63732049] bias: [151.3115503]
Epoch: 2570 / 5000
w1: [28.23385952] w2: [4.66719725] w3: [102.54887718] w4: [75.75890227] bias: [152.43789515]
Epoch: 2571 / 5000
w1: [28.23876028] w2: [4.67633584] w3: [102.54775813] w4: [75.7640879] bias: [152.61821425]
Epoch: 2572 / 5000
w1: [28.18674236] w2: [4.60709851] w3: [102.56654375] w4: [75.78594512] bias: [151.25205059]
Epoch: 2573 / 5000
w1: [28.16950311] w2: [4.59250571] w3: [102.56240116] w4: [75.76608473] bias: [151.57893818]
Epoch: 2574 / 5000
w1: [28.15208758] w2: [4.58472806] w3: [102.55831544] w4: [75.75489974] bias: [151.75316222]
Epoch: 2575 / 5000
w1: [28.21357099] w2: [4.68586089] w3: [102.67712944] w4: [75.8672489] bias: [153.74867509]
Epoch: 2576 / 5000
w1: [28.17803743] w2: [4.78329396] w3: [102.62010261] w4: [75.73933427] bias: [151.5661148]
Epoch: 2577 / 5000
w1: [28.1363323] w2: [4.7639664] w3: [102.58988412] w4: [75.71004884] bias: [151.99906392]
Epoch: 2578 / 5000
w1: [28.10137373] w2: [4.85982286] w3: [102.53378007] w4: [75.58420405] bias: [149.85182059]
Epoch: 2579 / 5000
w1: [28.0739338] w2: [4.93506317] w3: [102.57512156] w4: [75.52412896] bias: [148.16639138]
Epoch: 2580 / 5000
w1: [28.24655871] w2: [5.06537512] w3: [102.55916442] w4: [75.68659837] bias: [150.73765509]
Epoch: 2581 / 5000
w1: [28.2220926] w2: [5.13246123] w3: [102.65433482] w4: [75.77272689] bias: [149.23488528]
Epoch: 2582 / 5000
w1: [28.32409085] w2: [5.03444221] w3: [102.73304372] w4: [75.90355092] bias: [147.30081286]
Epoch: 2583 / 5000
w1: [28.38546269] w2: [4.9455209] w3: [102.74429786] w4: [75.92654498] bias: [149.2927046]
Epoch: 2584 / 5000
w1: [28.3711369] w2: [4.89547825] w3: [102.81225024] w4: [75.98579811] bias: [150.41369068]
Epoch: 2585 / 5000
w1: [28.52149769] w2: [4.8219183] w3: [102.84628825] w4: [76.01901421] bias: [148.96223498]
Epoch: 2586 / 5000
w1: [28.48699822] w2: [4.77999784] w3: [102.87281805] w4: [76.03794345] bias: [148.13507713]
Epoch: 2587 / 5000
w1: [28.53364687] w2: [4.82493865] w3: [102.86444763] w4: [76.08176258] bias: [149.02183134]
Epoch: 2588 / 5000
w1: [28.48168835] w2: [4.88284761] w3: [102.93740707] w4: [76.16182975] bias: [150.16446791]
Epoch: 2589 / 5000
w1: [28.54486655] w2: [4.79130907] w3: [103.15231932] w4: [76.31963362] bias: [152.21498729]
Epoch: 2590 / 5000
w1: [28.54944333] w2: [4.74924737] w3: [103.16552064] w4: [76.37577253] bias: [151.38504252]
Epoch: 2591 / 5000
w1: [28.63059715] w2: [4.81794299] w3: [103.18778851] w4: [76.4147534] bias: [152.74051738]
Epoch: 2592 / 5000
w1: [28.67861464] w2: [4.79565966] w3: [103.20782479] w4: [76.38614492] bias: [153.23967774]
Epoch: 2593 / 5000
w1: [28.69464867] w2: [4.87391242] w3: [103.31694725] w4: [76.51678481] bias: [151.48676796]
Epoch: 2594 / 5000
w1: [28.68371293] w2: [4.93450267] w3: [103.28375636] w4: [76.52646988] bias: [152.68231073]
Epoch: 2595 / 5000
w1: [28.63482865] w2: [4.85459452] w3: [103.4269897] w4: [76.70323376] bias: [154.47230215]
Epoch: 2596 / 5000
w1: [28.63882102] w2: [4.88691371] w3: [103.40963414] w4: [76.6973689] bias: [153.74833252]
Epoch: 2597 / 5000
w1: [28.74478158] w2: [4.99656672] w3: [103.53612592] w4: [76.8489794] bias: [155.91196211]
Epoch: 2598 / 5000
w1: [28.6950153] w2: [4.9589989] w3: [103.54711785] w4: [76.80553515] bias: [155.17068894]
Epoch: 2599 / 5000
w1: [28.85509452] w2: [4.88068448] w3: [103.58335587] w4: [76.84089814] bias: [153.62541977]
Epoch: 2600 / 5000
w1: [28.80993101] w2: [4.78347409] w3: [103.64280911] w4: [76.85177467] bias: [151.70730304]
Epoch: 2601 / 5000
w1: [28.98338426] w2: [4.68057593] w3: [103.70574096] w4: [76.89823848] bias: [149.67695737]
Epoch: 2602 / 5000
w1: [29.03889634] w2: [4.74543641] w3: [103.60827181] w4: [76.9865118] bias: [148.22404289]
Epoch: 2603 / 5000
w1: [29.0388217] w2: [4.74540182] w3: [103.60821271] w4: [76.98647806] bias: [148.22481778]
Epoch: 2604 / 5000
w1: [28.92166676] w2: [4.65190446] w3: [103.61170816] w4: [76.86355653] bias: [146.37996485]
Epoch: 2605 / 5000
w1: [29.05795886] w2: [4.74950826] w3: [103.59768051] w4: [76.95872424] bias: [148.30584448]
Epoch: 2606 / 5000
w1: [28.94135117] w2: [4.82511329] w3: [103.71383776] w4: [77.03757832] bias: [149.79765289]
Epoch: 2607 / 5000
w1: [28.99818581] w2: [4.74180461] w3: [103.70455025] w4: [77.04689944] bias: [148.15383905]
Epoch: 2608 / 5000
w1: [29.02138659] w2: [4.83476835] w3: [103.77027171] w4: [77.1375429] bias: [149.98816273]
Epoch: 2609 / 5000
w1: [29.03321309] w2: [4.73669134] w3: [103.64297634] w4: [77.0872656] bias: [152.18514792]
Epoch: 2610 / 5000
w1: [29.00341206] w2: [4.69284197] w3: [103.64461567] w4: [77.09812939] bias: [151.31992962]
Epoch: 2611 / 5000
w1: [29.00651409] w2: [4.69469994] w3: [103.6455917] w4: [77.09836539] bias: [151.27830992]
Epoch: 2612 / 5000
w1: [28.9647338] w2: [4.66539004] w3: [103.66911539] w4: [77.08334023] bias: [151.93486964]
Epoch: 2613 / 5000
w1: [28.92328704] w2: [4.64618222] w3: [103.6390841] w4: [77.05423623] bias: [152.36513658]
Epoch: 2614 / 5000
w1: [28.92222856] w2: [4.65590989] w3: [103.63747916] w4: [77.05380866] bias: [152.55707905]
Epoch: 2615 / 5000
w1: [28.87537486] w2: [4.61331494] w3: [103.64184171] w4: [77.06482325] bias: [153.51123207]
Epoch: 2616 / 5000
w1: [28.86810504] w2: [4.57783517] w3: [103.59664869] w4: [77.02474507] bias: [154.30600054]
Epoch: 2617 / 5000
w1: [28.88801633] w2: [4.6897641] w3: [103.74956978] w4: [77.15669136] bias: [156.51453774]
Epoch: 2618 / 5000
w1: [28.88099548] w2: [4.62366462] w3: [103.78718432] w4: [77.16857733] bias: [155.21028908]
Epoch: 2619 / 5000
w1: [28.85357546] w2: [4.64831687] w3: [103.78206845] w4: [77.18089138] bias: [155.69671743]
Epoch: 2620 / 5000
w1: [28.91676387] w2: [4.72214638] w3: [103.87254515] w4: [77.3098407] bias: [154.04289113]
Epoch: 2621 / 5000
w1: [28.97009217] w2: [4.62318243] w3: [103.88676829] w4: [77.38814259] bias: [152.09017365]
Epoch: 2622 / 5000
w1: [28.87650544] w2: [4.76036262] w3: [103.88455713] w4: [77.57781325] bias: [154.79695883]
Epoch: 2623 / 5000
w1: [28.85948516] w2: [4.69216367] w3: [103.98138177] w4: [77.64103928] bias: [153.45128422]
Epoch: 2624 / 5000
w1: [28.88011695] w2: [4.7086292] w3: [103.97306242] w4: [77.64478977] bias: [153.77617551]
Epoch: 2625 / 5000
w1: [28.77604685] w2: [4.63006824] w3: [104.03781732] w4: [77.62689528] bias: [152.22604181]
Epoch: 2626 / 5000
w1: [28.8101256] w2: [4.69432112] w3: [104.10414764] w4: [77.67469921] bias: [150.78673806]
Epoch: 2627 / 5000
w1: [28.79412596] w2: [4.63021181] w3: [104.19516606] w4: [77.73413381] bias: [149.52175864]
Epoch: 2628 / 5000
w1: [28.8578479] w2: [4.56747274] w3: [104.18644425] w4: [77.71164895] bias: [150.92715233]
Epoch: 2629 / 5000
w1: [28.84588169] w2: [4.60970751] w3: [104.21067023] w4: [77.74958594] bias: [149.98106755]
Epoch: 2630 / 5000
w1: [28.84696605] w2: [4.60839403] w3: [104.21055174] w4: [77.75098209] bias: [149.95515054]
Epoch: 2631 / 5000
w1: [28.84613554] w2: [4.61299555] w3: [104.2089118] w4: [77.74796649] bias: [150.04594578]
Epoch: 2632 / 5000
w1: [28.83857484] w2: [4.62537914] w3: [104.21582295] w4: [77.76508853] bias: [150.29029391]
Epoch: 2633 / 5000
w1: [28.83892954] w2: [4.61633358] w3: [104.20255386] w4: [77.76393955] bias: [150.49292004]
Epoch: 2634 / 5000
w1: [28.94657606] w2: [4.7277313] w3: [104.36659464] w4: [77.91039478] bias: [152.69097563]
Epoch: 2635 / 5000
w1: [29.06662422] w2: [4.82353764] w3: [104.53416367] w4: [78.04286035] bias: [154.58138834]
Epoch: 2636 / 5000
w1: [29.14217288] w2: [4.77588079] w3: [104.60808127] w4: [78.08337412] bias: [155.64893093]
Epoch: 2637 / 5000
w1: [29.05020378] w2: [4.82204726] w3: [104.60112368] w4: [78.05719419] bias: [154.61477366]
Epoch: 2638 / 5000
w1: [29.01890029] w2: [4.80233733] w3: [104.57554192] w4: [78.0212491] bias: [155.05628816]
Epoch: 2639 / 5000
w1: [29.02506216] w2: [4.80490272] w3: [104.57750894] w4: [78.02513623] bias: [154.99882181]
Epoch: 2640 / 5000
w1: [28.96494671] w2: [4.86924585] w3: [104.58956069] w4: [78.06308276] bias: [153.55749639]
Epoch: 2641 / 5000
w1: [28.99092041] w2: [4.89827808] w3: [104.56933506] w4: [78.09927936] bias: [154.13034881]
Epoch: 2642 / 5000
w1: [29.07389414] w2: [4.82367968] w3: [104.65779395] w4: [78.15323513] bias: [152.65840275]
Epoch: 2643 / 5000
w1: [29.14270638] w2: [4.76095413] w3: [104.69602115] w4: [78.11783895] bias: [154.06349333]
Epoch: 2644 / 5000
w1: [29.14057641] w2: [4.69928855] w3: [104.70226088] w4: [78.13311675] bias: [152.84673251]
Epoch: 2645 / 5000
w1: [29.261635] w2: [4.64310925] w3: [104.76769516] w4: [78.23286749] bias: [154.10518336]
Epoch: 2646 / 5000
w1: [29.0845011] w2: [4.48207585] w3: [105.34793851] w4: [78.06338233] bias: [157.71242995]
Epoch: 2647 / 5000
w1: [29.11275621] w2: [4.57003118] w3: [105.35213242] w4: [78.05354132] bias: [159.44792949]
Epoch: 2648 / 5000
w1: [29.09375866] w2: [4.51089371] w3: [105.40465027] w4: [77.97981033] bias: [158.28105251]
Epoch: 2649 / 5000
w1: [29.13909055] w2: [4.42676909] w3: [105.44357682] w4: [78.00636725] bias: [156.62113882]
Epoch: 2650 / 5000
w1: [29.0696987] w2: [4.47904956] w3: [105.43050382] w4: [77.9650021] bias: [157.65271626]
Epoch: 2651 / 5000
w1: [29.08957106] w2: [4.40890999] w3: [105.39873869] w4: [77.939865] bias: [159.22388547]
Epoch: 2652 / 5000
w1: [29.11140941] w2: [4.45754626] w3: [105.37849205] w4: [77.84101692] bias: [158.13440325]
Epoch: 2653 / 5000
w1: [29.08915839] w2: [4.34895199] w3: [105.40534538] w4: [77.70159811] bias: [160.56698151]
Epoch: 2654 / 5000
w1: [29.09254087] w2: [4.33021116] w3: [105.40485033] w4: [77.70242184] bias: [160.19719493]
Epoch: 2655 / 5000
w1: [29.05149961] w2: [4.28225843] w3: [105.41555039] w4: [77.65195233] bias: [161.27136536]
Epoch: 2656 / 5000
w1: [29.11490459] w2: [4.23176164] w3: [105.49476] w4: [77.65760224] bias: [160.27498264]
Epoch: 2657 / 5000
w1: [29.21928844] w2: [4.35859893] w3: [105.67344428] w4: [77.6778766] bias: [162.7776857]
Epoch: 2658 / 5000
w1: [29.405924] w2: [4.24788059] w3: [105.72232175] w4: [77.67522163] bias: [160.59303533]
Epoch: 2659 / 5000
w1: [29.42275642] w2: [4.25796242] w3: [105.7276179] w4: [77.67650224] bias: [160.36719617]
Epoch: 2660 / 5000
w1: [29.49744814] w2: [4.33765566] w3: [105.84644543] w4: [77.76037815] bias: [158.58201872]
Epoch: 2661 / 5000
w1: [29.39210988] w2: [4.2937998] w3: [105.83505451] w4: [77.72098503] bias: [159.56441678]
Epoch: 2662 / 5000
w1: [29.41270474] w2: [4.31681981] w3: [105.81901736] w4: [77.74968576] bias: [160.01863852]
Epoch: 2663 / 5000
w1: [29.40246964] w2: [4.36749995] w3: [105.84196961] w4: [77.81084292] bias: [158.88337246]
Epoch: 2664 / 5000
w1: [29.43304177] w2: [4.33046836] w3: [105.86383034] w4: [77.81247059] bias: [158.15267986]
Epoch: 2665 / 5000
w1: [29.39447216] w2: [4.4020439] w3: [105.9494417] w4: [77.96491943] bias: [159.56497992]
Epoch: 2666 / 5000
w1: [29.49289273] w2: [4.33995922] w3: [105.94230982] w4: [77.95703338] bias: [160.95571477]
Epoch: 2667 / 5000
w1: [29.4918863] w2: [4.34108091] w3: [105.94176693] w4: [77.95835567] bias: [160.97784754]
Epoch: 2668 / 5000
w1: [29.45330957] w2: [4.3060106] w3: [105.94535881] w4: [77.96742447] bias: [161.76344401]
Epoch: 2669 / 5000
w1: [29.46015499] w2: [4.36142591] w3: [105.86475925] w4: [77.92317852] bias: [160.52210714]
Epoch: 2670 / 5000
w1: [29.52344546] w2: [4.43216915] w3: [105.89220435] w4: [77.97773869] bias: [161.91798482]
Epoch: 2671 / 5000
w1: [29.48240088] w2: [4.45946139] w3: [105.91576646] w4: [77.99383436] bias: [161.30662206]
Epoch: 2672 / 5000
w1: [29.42868725] w2: [4.40215096] w3: [105.83169677] w4: [77.94235581] bias: [162.59041059]
Epoch: 2673 / 5000
w1: [29.43145087] w2: [4.46770442] w3: [105.92627561] w4: [77.92540441] bias: [161.12197315]
Epoch: 2674 / 5000
w1: [29.29578379] w2: [4.37054821] w3: [105.98569571] w4: [77.883474] bias: [159.20492541]
Epoch: 2675 / 5000
w1: [29.27688048] w2: [4.31170408] w3: [106.03795307] w4: [77.81010874] bias: [158.04383633]
Epoch: 2676 / 5000
w1: [29.23543266] w2: [4.27402365] w3: [106.04181227] w4: [77.81985248] bias: [158.88790107]
Epoch: 2677 / 5000
w1: [29.19930733] w2: [4.37307938] w3: [106.03884175] w4: [77.80187714] bias: [156.66899201]
Epoch: 2678 / 5000
w1: [29.20186296] w2: [4.3042597] w3: [106.08385859] w4: [77.82673484] bias: [155.31106943]
Epoch: 2679 / 5000
w1: [29.168773] w2: [4.27001664] w3: [106.08149756] w4: [77.77938906] bias: [154.63539901]
Epoch: 2680 / 5000
w1: [29.13444573] w2: [4.19613029] w3: [106.13925668] w4: [77.78765595] bias: [153.17750277]

In [ ]:
predicted = features[:, 0]*w1 + features[:, 1]*w2 + features[:, 2]*w3 + features[:, 3]*w4 + bias
diabetesDF['SGD_PREDICTED_TARGET'] = predicted
diabetesDF.head(10)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target,SGD_PREDICTED_TARGET
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0,172.009121
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0,141.854375
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0,167.584729
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0,143.413399
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0,151.382886
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346,97.0,140.137998
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357,138.0,142.673419
7,0.063504,0.050680,-0.001895,0.066629,0.090620,0.108914,0.022869,0.017703,-0.035816,0.003064,63.0,167.492054
8,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014960,0.011349,110.0,163.996115
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504,310.0,154.136019

### iteration시마다 **일정한 batch 크기**만큼의 데이터를 <br> **random**하게 가져와서 GD를 수행하는 **Mini-Batch GD** 수행

In [ ]:
def get_update_weights_values_batch(bias, w1, w2, w3, w4, age_batch, sex_batch, bmi_batch, bp_batch, target_batch, learning_rate):

    # 데이터 개수
    N = target_batch.shape[0]
    # 예측값
    predicted_batch = w1 * age_batch + w2 * sex_batch + w3 * bmi_batch + w4 * bp_batch + bias
    # 실제값 - 예측값
    diff_batch = target_batch - predicted_batch
    # array 기반 bia 설정
    bias_factors = np.ones((N,))

    # weight와 bias를 얼마나 update할 것인지를 계산.
    w1_update = -(2/N) * learning_rate * np.dot(age_batch.T, diff_batch)
    w2_update = -(2/N) * learning_rate * np.dot(sex_batch.T, diff_batch)
    w3_update = -(2/N) * learning_rate * np.dot(bmi_batch.T, diff_batch)
    w4_update = -(2/N) * learning_rate * np.dot(bp_batch.T, diff_batch)
    bias_update = -(2/N) * learning_rate * np.dot(bias_factors.T, diff_batch)

    # Mean Squared Error값을 계산.
    #mse_loss = np.mean(np.square(diff))

    return bias_update, w1_update, w2_update, w3_update, w4_update

In [ ]:
batch_idxes = np.random.choice(442, 30)
print(batch_idxes)

diabetesDF['bmi'].values[batch_idxes]

[365 322 157 163 345 160  69 160 141 343  75 271 182  42  44 219 166 435
 217 432 167 411 169 416 391 420 215 131 313 376]

array([-0.03854032,  0.06169621, -0.03315126,  0.07247433, -0.00297252,
       -0.06225218, -0.046085  , -0.06225218,  0.04768465,  0.01858372,
       -0.03099563,  0.00888341,  0.00564998, -0.0105172 ,  0.06816308,
       -0.04177375, -0.06009656, -0.02345095,  0.03151747,  0.05522933,
        0.06924089,  0.05846277, -0.02668438,  0.08001901, -0.06979687,
       -0.03638469,  0.09403057, -0.06979687,  0.05307371,  0.06816308])

In [ ]:
def batch_random_gradient_descent(features, target, iter_epochs=1000, batch_size=30, verbose=True):
    np.random.seed = 2026
    w1 = np.zeros((1,))
    w2 = np.zeros((1,))
    w3 = np.zeros((1,))
    w4 = np.zeros((1,))
    bias = np.zeros((1,))
    print('initial w1, w2, w3, w4, bias:', w1, w2, w3, w4, bias)

    learning_rate = 0.01
    age = features[:, 0]
    sex = features[:, 1]
    bmi = features[:, 2]
    bp = features[:, 3]

    for i in range(iter_epochs):
        # batch_size 갯수만큼 데이터를 임의로 선택.
        batch_idxes = np.random.choice(target.shape[0], batch_size)
        age_batch = age[batch_idxes]
        sex_batch = sex[batch_idxes]
        bmi_batch = bmi[batch_idxes]
        bp_batch = bp[batch_idxes]
        target_batch = target[batch_idxes]
        # Batch GD 기반으로 Weight/Bias의 Update를 구함.
        bias_update, w1_update, w2_update, w3_update, w4_update = get_update_weights_values_batch(bias, w1, w2, w3, w4, age_batch, sex_batch, bmi_batch, bp_batch, target_batch, learning_rate)

        # Batch GD로 구한 weight/bias의 update 적용.
        w1 = w1 - w1_update
        w2 = w2 - w2_update
        w3 = w3 - w3_update
        w4 = w4 - w4_update
        bias = bias - bias_update
        if verbose:
            print('Epoch:', i+1, '/', iter_epochs)
            # 전체 학습 데이터 기반 Loss
            predicted = w1 * age + w2 * sex + w3 * bmi + w4 * bp + bias
            diff = target - predicted
            mse_loss = np.mean(np.square(diff))
            print('w1:', w1, 'w2:', w2, 'w3:', w3, 'w4:', w4, 'bias:', bias)

    return w1, w2, w3, w4, bias

In [ ]:
w1, w2, w3, w4, bias = batch_random_gradient_descent(features, diabetesDF['target'].values, iter_epochs=5000, batch_size=30, verbose=True)
print('##### 최종 w1, w2, w3, w4, bias #######')
print(w1, w2, w3, w4, bias)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
Epoch: 2502 / 5000
w1: [29.99767099] w2: [6.58698999] w3: [99.57716439] w4: [73.17925284] bias: [153.34608398]
Epoch: 2503 / 5000
w1: [30.01430714] w2: [6.57749608] w3: [99.62511641] w4: [73.20642596] bias: [153.55976079]
Epoch: 2504 / 5000
w1: [30.01347816] w2: [6.57887263] w3: [99.6661726] w4: [73.24562248] bias: [153.46332831]
Epoch: 2505 / 5000
w1: [30.01462607] w2: [6.56855004] w3: [99.71473448] w4: [73.25597499] bias: [153.79014211]
Epoch: 2506 / 5000
w1: [30.01468248] w2: [6.55358557] w3: [99.74358922] w4: [73.25918407] bias: [153.73701304]
Epoch: 2507 / 5000
w1: [30.03966132] w2: [6.55283855] w3: [99.76884403] w4: [73.29262744] bias: [153.65961701]
Epoch: 2508 / 5000
w1: [30.04405605] w2: [6.54685026] w3: [99.78624067] w4: [73.29795554] bias: [153.3596099]
Epoch: 2509 / 5000
w1: [30.05536589] w2: [6.54301993] w3: [99.81354223] w4: [73.32249764] bias: [153.32539048]
Epoch: 2510 / 5000
w1: [30.0691703] w2: [6.54210696] w3: [99.83780524] w4: [73.34114321] bias: [153.36471308]
Epoch: 2511 / 5000
w1: [30.06464352] w2: [6.55265835] w3: [99.8576798] w4: [73.37727893] bias: [153.07619103]
Epoch: 2512 / 5000
w1: [30.07941942] w2: [6.54151062] w3: [99.90751471] w4: [73.39377224] bias: [153.18122565]
Epoch: 2513 / 5000
w1: [30.09959282] w2: [6.54638503] w3: [99.95359943] w4: [73.41180378] bias: [153.26606573]
Epoch: 2514 / 5000
w1: [30.09948762] w2: [6.5381486] w3: [100.00057375] w4: [73.44988315] bias: [153.09271259]
Epoch: 2515 / 5000
w1: [30.09997621] w2: [6.54793692] w3: [100.02896986] w4: [73.47324589] bias: [152.85596844]
Epoch: 2516 / 5000
w1: [30.11392358] w2: [6.54699609] w3: [100.06326545] w4: [73.49753766] bias: [153.38828529]
Epoch: 2517 / 5000
w1: [30.13251642] w2: [6.55175046] w3: [100.10259703] w4: [73.52411942] bias: [152.74485268]
Epoch: 2518 / 5000
w1: [30.13093026] w2: [6.56150867] w3: [100.14327471] w4: [73.52839701] bias: [153.04623564]
Epoch: 2519 / 5000
w1: [30.15176746] w2: [6.56672406] w3: [100.21883578] w4: [73.58673248] bias: [153.05639612]
Epoch: 2520 / 5000
w1: [30.15251979] w2: [6.57979308] w3: [100.25065024] w4: [73.63730903] bias: [152.81359781]
Epoch: 2521 / 5000
w1: [30.18180482] w2: [6.57922552] w3: [100.28560259] w4: [73.66055839] bias: [152.8663217]
Epoch: 2522 / 5000
w1: [30.19937131] w2: [6.57017872] w3: [100.3509903] w4: [73.6899412] bias: [153.31319962]
Epoch: 2523 / 5000
w1: [30.19677261] w2: [6.56147739] w3: [100.38550109] w4: [73.70433353] bias: [153.15296968]
Epoch: 2524 / 5000
w1: [30.21722734] w2: [6.57000724] w3: [100.42667895] w4: [73.7322924] bias: [153.09430217]
Epoch: 2525 / 5000
w1: [30.21979236] w2: [6.56976476] w3: [100.46503063] w4: [73.75828163] bias: [153.24245029]
Epoch: 2526 / 5000
w1: [30.23951885] w2: [6.57972006] w3: [100.49183492] w4: [73.77951512] bias: [153.34027016]
Epoch: 2527 / 5000
w1: [30.25827674] w2: [6.60807795] w3: [100.53116039] w4: [73.7979745] bias: [153.15820763]
Epoch: 2528 / 5000
w1: [30.28211639] w2: [6.60940114] w3: [100.56517677] w4: [73.83884134] bias: [153.11837814]
Epoch: 2529 / 5000
w1: [30.28249648] w2: [6.60993519] w3: [100.59428614] w4: [73.86469617] bias: [152.99078823]
Epoch: 2530 / 5000
w1: [30.29488631] w2: [6.62368967] w3: [100.6230183] w4: [73.88093976] bias: [152.6765301]
Epoch: 2531 / 5000
w1: [30.29239283] w2: [6.61377906] w3: [100.67180931] w4: [73.91435823] bias: [153.06910163]
Epoch: 2532 / 5000
w1: [30.32832617] w2: [6.60794762] w3: [100.70560855] w4: [73.95080243] bias: [153.07401549]
Epoch: 2533 / 5000
w1: [30.33565168] w2: [6.59713752] w3: [100.7284239] w4: [73.95693755] bias: [153.07710524]
Epoch: 2534 / 5000
w1: [30.35407802] w2: [6.61020281] w3: [100.76671089] w4: [73.97944925] bias: [152.84148049]
Epoch: 2535 / 5000
w1: [30.34548028] w2: [6.59682089] w3: [100.8001729] w4: [73.99734042] bias: [152.61037647]
Epoch: 2536 / 5000
w1: [30.37491066] w2: [6.60666446] w3: [100.84698389] w4: [74.03988021] bias: [152.8526172]
Epoch: 2537 / 5000
w1: [30.37568214] w2: [6.60355164] w3: [100.86921855] w4: [74.05868921] bias: [152.36982279]
Epoch: 2538 / 5000
w1: [30.39967266] w2: [6.59979887] w3: [100.93950098] w4: [74.09739964] bias: [152.90780462]
Epoch: 2539 / 5000
w1: [30.40683858] w2: [6.58876247] w3: [100.9706175] w4: [74.11377935] bias: [152.73893089]
Epoch: 2540 / 5000
w1: [30.41114011] w2: [6.58620596] w3: [100.99976265] w4: [74.12930583] bias: [152.48320897]
Epoch: 2541 / 5000
w1: [30.42714252] w2: [6.58549327] w3: [101.03278368] w4: [74.14557022] bias: [152.42965561]
Epoch: 2542 / 5000
w1: [30.43985591] w2: [6.57712812] w3: [101.05363271] w4: [74.16644676] bias: [152.22648059]
Epoch: 2543 / 5000
w1: [30.45351795] w2: [6.59991503] w3: [101.07112208] w4: [74.20136054] bias: [152.22033762]
Epoch: 2544 / 5000
w1: [30.45587378] w2: [6.58123088] w3: [101.116601] w4: [74.23031996] bias: [152.49691053]
Epoch: 2545 / 5000
w1: [30.44546311] w2: [6.5726434] w3: [101.13563992] w4: [74.23940036] bias: [152.22851444]
Epoch: 2546 / 5000
w1: [30.4258298] w2: [6.5780049] w3: [101.17296728] w4: [74.24898502] bias: [152.12417049]
Epoch: 2547 / 5000
w1: [30.45658968] w2: [6.57881737] w3: [101.21541819] w4: [74.2925439] bias: [152.04215853]
Epoch: 2548 / 5000
w1: [30.47639223] w2: [6.59353535] w3: [101.24170729] w4: [74.30516104] bias: [151.76223266]
Epoch: 2549 / 5000
w1: [30.48646432] w2: [6.59198329] w3: [101.2759959] w4: [74.31117498] bias: [151.29214666]
Epoch: 2550 / 5000
w1: [30.51201375] w2: [6.59926093] w3: [101.33994045] w4: [74.35813609] bias: [151.37198921]
Epoch: 2551 / 5000
w1: [30.51700356] w2: [6.60688254] w3: [101.38045773] w4: [74.39289329] bias: [151.50895592]
Epoch: 2552 / 5000
w1: [30.53140011] w2: [6.60571067] w3: [101.43211406] w4: [74.41728419] bias: [151.76632464]
Epoch: 2553 / 5000
w1: [30.53828287] w2: [6.59102347] w3: [101.46389469] w4: [74.41906515] bias: [151.77015604]
Epoch: 2554 / 5000
w1: [30.53313554] w2: [6.59750018] w3: [101.5154839] w4: [74.45506011] bias: [152.29950598]
Epoch: 2555 / 5000
w1: [30.53926157] w2: [6.60253624] w3: [101.53274701] w4: [74.47769032] bias: [151.86734255]
Epoch: 2556 / 5000
w1: [30.56360529] w2: [6.63533326] w3: [101.58493488] w4: [74.5205908] bias: [152.09889241]
Epoch: 2557 / 5000
w1: [30.57658729] w2: [6.62820697] w3: [101.62643202] w4: [74.54467783] bias: [152.61571643]
Epoch: 2558 / 5000
w1: [30.59265439] w2: [6.62843416] w3: [101.67127827] w4: [74.58001893] bias: [152.76721466]
Epoch: 2559 / 5000
w1: [30.60772194] w2: [6.60779358] w3: [101.69545554] w4: [74.5754768] bias: [153.08614132]
Epoch: 2560 / 5000
w1: [30.63264114] w2: [6.60849151] w3: [101.73119907] w4: [74.61683227] bias: [152.82114861]
Epoch: 2561 / 5000
w1: [30.64410317] w2: [6.61389751] w3: [101.77003967] w4: [74.65883958] bias: [152.64092255]
Epoch: 2562 / 5000
w1: [30.6613553] w2: [6.6336946] w3: [101.83191587] w4: [74.70670212] bias: [152.77746251]
Epoch: 2563 / 5000
w1: [30.67097644] w2: [6.62189015] w3: [101.87675032] w4: [74.74351028] bias: [152.69346925]
Epoch: 2564 / 5000
w1: [30.68492378] w2: [6.62478909] w3: [101.9104092] w4: [74.77697247] bias: [152.92263099]
Epoch: 2565 / 5000
w1: [30.71593789] w2: [6.61899455] w3: [101.96859227] w4: [74.80723337] bias: [153.30215155]
Epoch: 2566 / 5000
w1: [30.72760797] w2: [6.60061776] w3: [102.00625686] w4: [74.82924914] bias: [153.14142862]
Epoch: 2567 / 5000
w1: [30.72938762] w2: [6.6064728] w3: [102.04961656] w4: [74.85315177] bias: [153.10894571]
Epoch: 2568 / 5000
w1: [30.73426359] w2: [6.5862052] w3: [102.09232954] w4: [74.88176196] bias: [152.7953495]
Epoch: 2569 / 5000
w1: [30.73966996] w2: [6.58592679] w3: [102.134488] w4: [74.91197992] bias: [153.14323648]
Epoch: 2570 / 5000
w1: [30.75251526] w2: [6.60158856] w3: [102.16330756] w4: [74.95228825] bias: [153.16289866]
Epoch: 2571 / 5000
w1: [30.77486648] w2: [6.61718109] w3: [102.20246347] w4: [74.9806204] bias: [152.76877091]
Epoch: 2572 / 5000
w1: [30.78623899] w2: [6.62181735] w3: [102.22487621] w4: [75.01310221] bias: [152.81205943]
Epoch: 2573 / 5000
w1: [30.77738738] w2: [6.61486013] w3: [102.26125692] w4: [75.04015261] bias: [152.66575841]
Epoch: 2574 / 5000
w1: [30.78533525] w2: [6.61124542] w3: [102.28392772] w4: [75.06015435] bias: [152.66945791]
Epoch: 2575 / 5000
w1: [30.79369312] w2: [6.60189263] w3: [102.33186828] w4: [75.09489887] bias: [152.46231659]
Epoch: 2576 / 5000
w1: [30.80706758] w2: [6.60222381] w3: [102.36878066] w4: [75.12505619] bias: [152.26181978]
Epoch: 2577 / 5000
w1: [30.80568681] w2: [6.58357956] w3: [102.42996103] w4: [75.14510634] bias: [152.63796381]
Epoch: 2578 / 5000
w1: [30.7963182] w2: [6.57397159] w3: [102.45049814] w4: [75.15451055] bias: [152.06254262]
Epoch: 2579 / 5000
w1: [30.7999916] w2: [6.57110996] w3: [102.4561242] w4: [75.15792764] bias: [152.06145578]
Epoch: 2580 / 5000
w1: [30.79795807] w2: [6.56682672] w3: [102.49767082] w4: [75.17878639] bias: [151.81370264]
Epoch: 2581 / 5000
w1: [30.82043204] w2: [6.5753894] w3: [102.51914725] w4: [75.20495186] bias: [151.46774844]
Epoch: 2582 / 5000
w1: [30.84768389] w2: [6.57626323] w3: [102.56272974] w4: [75.24113779] bias: [151.5227565]
Epoch: 2583 / 5000
w1: [30.86264534] w2: [6.59095956] w3: [102.60559513] w4: [75.27569814] bias: [151.44882341]
Epoch: 2584 / 5000
w1: [30.84902979] w2: [6.58733673] w3: [102.64217907] w4: [75.29961969] bias: [151.69691338]
Epoch: 2585 / 5000
w1: [30.86798724] w2: [6.58215542] w3: [102.6783672] w4: [75.32428342] bias: [151.76878447]
Epoch: 2586 / 5000
w1: [30.88446887] w2: [6.5693493] w3: [102.71544647] w4: [75.35500256] bias: [151.84637074]
Epoch: 2587 / 5000
w1: [30.9215049] w2: [6.57177113] w3: [102.7602918] w4: [75.39927999] bias: [152.09410841]
Epoch: 2588 / 5000
w1: [30.93030842] w2: [6.55522906] w3: [102.80922993] w4: [75.41366749] bias: [152.28325056]
Epoch: 2589 / 5000
w1: [30.90526314] w2: [6.55169031] w3: [102.83911724] w4: [75.40522468] bias: [152.49466532]
Epoch: 2590 / 5000
w1: [30.91911595] w2: [6.55955721] w3: [102.85641396] w4: [75.42499488] bias: [152.06361994]
Epoch: 2591 / 5000
w1: [30.93074463] w2: [6.5802545] w3: [102.89110608] w4: [75.42995202] bias: [151.70522457]
Epoch: 2592 / 5000
w1: [30.92793555] w2: [6.58714925] w3: [102.9429907] w4: [75.4725596] bias: [151.85526976]
Epoch: 2593 / 5000
w1: [30.95165845] w2: [6.58268801] w3: [102.98493737] w4: [75.51409339] bias: [151.85976082]
Epoch: 2594 / 5000
w1: [30.96629091] w2: [6.59259252] w3: [103.01499488] w4: [75.55055621] bias: [152.18004451]
Epoch: 2595 / 5000
w1: [30.97329163] w2: [6.60123332] w3: [103.0751881] w4: [75.59570636] bias: [152.58653613]
Epoch: 2596 / 5000
w1: [31.00081077] w2: [6.56930584] w3: [103.11142981] w4: [75.61466808] bias: [152.53090164]
Epoch: 2597 / 5000
w1: [30.998969] w2: [6.57301576] w3: [103.16197426] w4: [75.63648251] bias: [152.71933833]
Epoch: 2598 / 5000
w1: [31.01963309] w2: [6.57138839] w3: [103.19871613] w4: [75.65100912] bias: [152.89465841]
Epoch: 2599 / 5000
w1: [31.02998637] w2: [6.57280008] w3: [103.26720417] w4: [75.67707688] bias: [152.91622472]
Epoch: 2600 / 5000
w1: [31.02791826] w2: [6.57919872] w3: [103.2888801] w4: [75.71262092] bias: [152.97914183]
Epoch: 2601 / 5000
w1: [31.03607559] w2: [6.57349155] w3: [103.32549457] w4: [75.76125249] bias: [153.33400288]
Epoch: 2602 / 5000
w1: [31.05616535] w2: [6.58976389] w3: [103.36593084] w4: [75.79904205] bias: [153.55166605]
Epoch: 2603 / 5000
w1: [31.05378638] w2: [6.57294436] w3: [103.39411151] w4: [75.8111094] bias: [153.20066317]
Epoch: 2604 / 5000
w1: [31.07652907] w2: [6.57859139] w3: [103.40967377] w4: [75.84499802] bias: [153.31681748]
Epoch: 2605 / 5000
w1: [31.09552818] w2: [6.58438458] w3: [103.44176277] w4: [75.86582478] bias: [152.99218775]
Epoch: 2606 / 5000
w1: [31.1237468] w2: [6.58581533] w3: [103.4734283] w4: [75.9082561] bias: [153.09471436]
Epoch: 2607 / 5000
w1: [31.12227526] w2: [6.57454339] w3: [103.48676757] w4: [75.91819891] bias: [152.84931373]
Epoch: 2608 / 5000
w1: [31.12292645] w2: [6.57372526] w3: [103.52123989] w4: [75.91682897] bias: [152.43116631]
Epoch: 2609 / 5000
w1: [31.12203212] w2: [6.60723396] w3: [103.58228534] w4: [75.96134031] bias: [152.89339815]
Epoch: 2610 / 5000
w1: [31.13383266] w2: [6.61253078] w3: [103.60755307] w4: [76.00012004] bias: [152.73060655]
Epoch: 2611 / 5000
w1: [31.13931537] w2: [6.62214675] w3: [103.64300606] w4: [76.03477548] bias: [153.0096594]
Epoch: 2612 / 5000
w1: [31.15983394] w2: [6.63335948] w3: [103.67889339] w4: [76.06719744] bias: [153.73884924]
Epoch: 2613 / 5000
w1: [31.16337703] w2: [6.64385744] w3: [103.73902296] w4: [76.10522282] bias: [153.88882417]
Epoch: 2614 / 5000
w1: [31.18481771] w2: [6.62510358] w3: [103.76530594] w4: [76.14137076] bias: [153.68172794]
Epoch: 2615 / 5000
w1: [31.18270903] w2: [6.59815626] w3: [103.79021317] w4: [76.16164696] bias: [154.18588007]
Epoch: 2616 / 5000
w1: [31.18149856] w2: [6.58926846] w3: [103.81641978] w4: [76.17863205] bias: [153.71486383]
Epoch: 2617 / 5000
w1: [31.19195231] w2: [6.59062722] w3: [103.85812538] w4: [76.19454816] bias: [153.87043504]
Epoch: 2618 / 5000
w1: [31.21060907] w2: [6.60214318] w3: [103.90423766] w4: [76.23289442] bias: [153.85352398]
Epoch: 2619 / 5000
w1: [31.23526062] w2: [6.61438677] w3: [103.96524505] w4: [76.27802316] bias: [154.08479922]
Epoch: 2620 / 5000
w1: [31.25417016] w2: [6.61913553] w3: [103.98132701] w4: [76.30749283] bias: [153.71679138]
Epoch: 2621 / 5000
w1: [31.26618101] w2: [6.62587985] w3: [104.01656132] w4: [76.33457353] bias: [154.17090546]
Epoch: 2622 / 5000
w1: [31.28131134] w2: [6.6332406] w3: [104.05739998] w4: [76.36558563] bias: [154.02193275]
Epoch: 2623 / 5000
w1: [31.2943168] w2: [6.63622963] w3: [104.08853351] w4: [76.3942134] bias: [153.52728561]
Epoch: 2624 / 5000
w1: [31.31906326] w2: [6.66482062] w3: [104.13976036] w4: [76.43826137] bias: [153.57467759]
Epoch: 2625 / 5000
w1: [31.31143465] w2: [6.65619486] w3: [104.18442589] w4: [76.47266134] bias: [153.46215895]
Epoch: 2626 / 5000
w1: [31.29483537] w2: [6.66443034] w3: [104.26027822] w4: [76.47682601] bias: [153.42860392]
Epoch: 2627 / 5000
w1: [31.32134942] w2: [6.66490121] w3: [104.30061012] w4: [76.50820613] bias: [153.11176377]
Epoch: 2628 / 5000
w1: [31.32936521] w2: [6.65628674] w3: [104.32147789] w4: [76.51961744] bias: [153.23120246]
Epoch: 2629 / 5000
w1: [31.35967579] w2: [6.65879016] w3: [104.37156198] w4: [76.55147347] bias: [153.09703276]
Epoch: 2630 / 5000
w1: [31.36804752] w2: [6.65382034] w3: [104.39662973] w4: [76.57225197] bias: [153.12730246]
Epoch: 2631 / 5000
w1: [31.37614197] w2: [6.66165815] w3: [104.43048263] w4: [76.60423295] bias: [152.81582228]
Epoch: 2632 / 5000
w1: [31.37007102] w2: [6.65673068] w3: [104.46652733] w4: [76.639869] bias: [153.15728722]
Epoch: 2633 / 5000
w1: [31.37088997] w2: [6.65325048] w3: [104.49495326] w4: [76.66694973] bias: [153.1805519]
Epoch: 2634 / 5000
w1: [31.38002405] w2: [6.65239802] w3: [104.53417506] w4: [76.69871741] bias: [153.7109285]
Epoch: 2635 / 5000
w1: [31.36870236] w2: [6.65457929] w3: [104.56587549] w4: [76.69572925] bias: [153.86015093]
Epoch: 2636 / 5000
w1: [31.36367134] w2: [6.65710192] w3: [104.59822969] w4: [76.71966697] bias: [153.7296708]
Epoch: 2637 / 5000
w1: [31.38097497] w2: [6.6557928] w3: [104.63984542] w4: [76.74457425] bias: [153.95271852]
Epoch: 2638 / 5000
w1: [31.39068803] w2: [6.65001249] w3: [104.68488367] w4: [76.77517484] bias: [153.67571088]
Epoch: 2639 / 5000
w1: [31.39182792] w2: [6.65342456] w3: [104.73620946] w4: [76.77668661] bias: [153.83817389]
Epoch: 2640 / 5000
w1: [31.41248134] w2: [6.66512281] w3: [104.76316252] w4: [76.79591994] bias: [153.88193545]
Epoch: 2641 / 5000
w1: [31.42388248] w2: [6.68389727] w3: [104.80241967] w4: [76.80429215] bias: [153.56109078]
Epoch: 2642 / 5000
w1: [31.45000295] w2: [6.6887547] w3: [104.84929311] w4: [76.8399778] bias: [153.62807487]
Epoch: 2643 / 5000
w1: [31.43961519] w2: [6.69422051] w3: [104.87189828] w4: [76.8605131] bias: [153.64858849]
Epoch: 2644 / 5000
w1: [31.43974265] w2: [6.69983463] w3: [104.90882532] w4: [76.88408927] bias: [154.05168899]
Epoch: 2645 / 5000
w1: [31.42641754] w2: [6.71108891] w3: [104.92238453] w4: [76.90408022] bias: [154.39762039]
Epoch: 2646 / 5000
w1: [31.4341597] w2: [6.70535559] w3: [104.9544701] w4: [76.93463274] bias: [154.34360112]
Epoch: 2647 / 5000
w1: [31.44989549] w2: [6.69734011] w3: [104.99435933] w4: [76.97622252] bias: [154.31899399]
Epoch: 2648 / 5000
w1: [31.46019725] w2: [6.70075915] w3: [105.0287671] w4: [76.99493616] bias: [154.07643418]
Epoch: 2649 / 5000
w1: [31.47082452] w2: [6.70347176] w3: [105.03952442] w4: [77.01876481] bias: [154.29524104]
Epoch: 2650 / 5000
w1: [31.49042162] w2: [6.72380698] w3: [105.11176634] w4: [77.06722199] bias: [154.2992874]
Epoch: 2651 / 5000
w1: [31.52297441] w2: [6.7162004] w3: [105.12489233] w4: [77.11117666] bias: [154.27100733]
Epoch: 2652 / 5000
w1: [31.52791572] w2: [6.73366074] w3: [105.16773886] w4: [77.14075546] bias: [154.25768042]
Epoch: 2653 / 5000
w1: [31.54951105] w2: [6.74939423] w3: [105.17409529] w4: [77.17391542] bias: [154.38606946]
Epoch: 2654 / 5000
w1: [31.57642211] w2: [6.75005818] w3: [105.21408778] w4: [77.20373413] bias: [154.60783178]
Epoch: 2655 / 5000
w1: [31.58013992] w2: [6.75844909] w3: [105.23076689] w4: [77.22300327] bias: [154.18139103]
Epoch: 2656 / 5000
w1: [31.57877001] w2: [6.73331161] w3: [105.25999933] w4: [77.25499683] bias: [153.96439617]
Epoch: 2657 / 5000
w1: [31.59510184] w2: [6.71632922] w3: [105.3004284] w4: [77.25490517] bias: [154.16642616]
Epoch: 2658 / 5000
w1: [31.62599485] w2: [6.71842142] w3: [105.33136463] w4: [77.26364933] bias: [153.71884716]
Epoch: 2659 / 5000
w1: [31.65093737] w2: [6.74727498] w3: [105.36018721] w4: [77.29732668] bias: [153.52297108]
Epoch: 2660 / 5000
w1: [31.65381736] w2: [6.74522751] w3: [105.39191126] w4: [77.32433561] bias: [153.48339645]
Epoch: 2661 / 5000
w1: [31.66878648] w2: [6.74575698] w3: [105.42412135] w4: [77.3570609] bias: [153.65084393]
Epoch: 2662 / 5000
w1: [31.67367759] w2: [6.74847919] w3: [105.47028745] w4: [77.37861517] bias: [153.85305957]
Epoch: 2663 / 5000
w1: [31.68857329] w2: [6.72640955] w3: [105.4891669] w4: [77.39881537] bias: [153.88910467]
Epoch: 2664 / 5000
w1: [31.69500232] w2: [6.74535966] w3: [105.53889563] w4: [77.43482159] bias: [154.03839756]
Epoch: 2665 / 5000
w1: [31.69444355] w2: [6.74602429] w3: [105.56750724] w4: [77.45380398] bias: [154.10674218]
Epoch: 2666 / 5000
w1: [31.6913539] w2: [6.72200045] w3: [105.60383749] w4: [77.47422075] bias: [154.2079346]
Epoch: 2667 / 5000
w1: [31.70311805] w2: [6.71897707] w3: [105.6387061] w4: [77.50272438] bias: [154.16325923]
Epoch: 2668 / 5000
w1: [31.70222091] w2: [6.71340842] w3: [105.67857423] w4: [77.51529394] bias: [154.09412628]
Epoch: 2669 / 5000
w1: [31.71879398] w2: [6.70152705] w3: [105.71573369] w4: [77.53115588] bias: [153.90189244]
Epoch: 2670 / 5000
w1: [31.71092245] w2: [6.67080182] w3: [105.76768694] w4: [77.55351936] bias: [154.17077418]
Epoch: 2671 / 5000
w1: [31.72632699] w2: [6.66871292] w3: [105.80309743] w4: [77.58204418] bias: [153.91417957]
Epoch: 2672 / 5000
w1: [31.73585897] w2: [6.66478561] w3: [105.82618205] w4: [77.60359159] bias: [153.59607182]
Epoch: 2673 / 5000
w1: [31.75373328] w2: [6.66713309] w3: [105.85905542] w4: [77.6258682] bias: [153.44155636]
Epoch: 2674 / 5000
w1: [31.76610115] w2: [6.66645491] w3: [105.89522541] w4: [77.66357214] bias: [152.88287857]
Epoch: 2675 / 5000
w1: [31.77018585] w2: [6.67021534] w3: [105.91211802] w4: [77.67363469] bias: [152.68667726]
Epoch: 2676 / 5000
w1: [31.79353643] w2: [6.68504854] w3: [105.95696379] w4: [77.70503538] bias: [152.69803251]
Epoch: 2677 / 5000
w1: [31.80993105] w2: [6.68508389] w3: [105.9794865] w4: [77.73739411] bias: [152.70915638]
Epoch: 2678 / 5000
w1: [31.81344941] w2: [6.68900253] w3: [106.01165052] w4: [77.77271896] bias: [152.92746862]
Epoch: 2679 / 5000
w1: [31.82145983] w2: [6.69590811] w3: [106.0458995] w4: [77.79097299] bias: [153.1725267]
Epoch: 2680 / 5000
w1: [31.83038807] w2: [6.69328236] w3: [106.06949125] w4: [77.793748] bias: [152.97747095]

In [ ]:
predicted = features[:, 0]*w1 + features[:, 1]*w2 + features[:, 2]*w3 + features[:, 3]*w4 + bias
diabetesDF['BATCH_PREDICTED_TARGET'] = predicted
diabetesDF.head(10)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target,BATCH_PREDICTED_TARGET
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0,168.630958
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0,138.382023
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0,164.258531
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0,139.716710
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0,148.043409
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346,97.0,136.451885
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357,138.0,138.930860
7,0.063504,0.050680,-0.001895,0.066629,0.090620,0.108914,0.022869,0.017703,-0.035816,0.003064,63.0,164.238981
8,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014960,0.011349,110.0,160.492391
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504,310.0,150.524353

### iteration 시에 순차적으로 일정한 batch 크기만큼의 데이터를<br> 전체 학습데이터에 걸쳐서 가져오는 Mini-Batch GD 수행

In [ ]:
for batch_step in range(0, 442, 30):
    print(batch_step)

0
30
60
90
120
150
180
210
240
270
300
330
360
390
420

In [ ]:
diabetesDF['target'].values[420:450]

array([146., 212., 233.,  91., 111., 152., 120.,  67., 310.,  94., 183.,
        66., 173.,  72.,  49.,  64.,  48., 178., 104., 132., 220.,  57.])

In [ ]:
def batch_gradient_descent(features, target, iter_epochs=1000, batch_size=30, verbose=True):
    np.random.seed = 2026
    w1 = np.zeros((1,))
    w2 = np.zeros((1,))
    w3 = np.zeros((1,))
    w4 = np.zeros((1,))
    bias = np.zeros((1,))
    print('initial w1, w2, w3, w4, bias:', w1, w2, w3, w4, bias)

    learning_rate = 0.01
    age = features[:, 0]
    sex = features[:, 1]
    bmi = features[:, 2]
    bp = features[:, 3]

    for i in range(iter_epochs):
        for batch_step in range(0, target.shape[0], batch_size):
            age_batch = age[batch_step:batch_step + batch_size]
            sex_batch = sex[batch_step:batch_step + batch_size]
            bmi_batch = bmi[batch_step:batch_step + batch_size]
            bp_batch = bp[batch_step:batch_step + batch_size]
            target_batch = target[batch_step:batch_step + batch_size]

            bias_update, w1_update, w2_update, w3_update, w4_update = get_update_weights_values_batch(bias, w1, w2, w3, w4, age_batch, sex_batch, bmi_batch, bp_batch, target_batch, learning_rate)

            w1 = w1 - w1_update
            w2 = w2 - w2_update
            w3 = w3 - w3_update
            w4 = w4 - w4_update
            bias = bias - bias_update

            if verbose:
                print('Epoch:', i+1, '/', iter_epochs, 'batch_step:', batch_step)

                predicted = w1 * age + w2 * sex + w3 * bmi + w4 * bp + bias
                diff = target - predicted
                mse_loss = np.mean(np.square(diff))
                print('w1:', w1, 'w2:', w2, 'w3:', w3, 'w4:', w4, 'bias:', bias)

    return w1, w2, w3, w4, bias

In [ ]:
w1, w2, w3, w4, bias = batch_gradient_descent(features, diabetesDF['target'].values, iter_epochs=5000, batch_size=30, verbose=True)
print('##### 최종 w1, w2, w3, w4, bias #######')
print(w1, w2, w3, w4, bias)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
Epoch: 4834 / 5000 batch_step: 180
w1: [50.79977035] w2: [-97.00624565] w3: [758.28529309] w4: [419.35166816] bias: [151.8080109]
Epoch: 4834 / 5000 batch_step: 210
w1: [50.77382137] w2: [-96.99847658] w3: [758.28287039] w4: [419.35054066] bias: [151.94846082]
Epoch: 4834 / 5000 batch_step: 240
w1: [50.77099997] w2: [-96.99361752] w3: [758.30995615] w4: [419.36060887] bias: [151.76350529]
Epoch: 4834 / 5000 batch_step: 270
w1: [50.7922525] w2: [-96.99874547] w3: [758.30884732] w4: [419.37054062] bias: [151.88132597]
Epoch: 4834 / 5000 batch_step: 300
w1: [50.80207268] w2: [-96.99029282] w3: [758.29541559] w4: [419.37118113] bias: [151.87131381]
Epoch: 4834 / 5000 batch_step: 330
w1: [50.80336568] w2: [-96.99074577] w3: [758.30589017] w4: [419.36367468] bias: [152.08181616]
Epoch: 4834 / 5000 batch_step: 360
w1: [50.8002799] w2: [-96.98184939] w3: [758.29923114] w4: [419.36058556] bias: [152.08769518]
Epoch: 4834 / 5000 batch_step: 390
w1: [50.81342882] w2: [-96.97871054] w3: [758.29852485] w4: [419.37757439] bias: [152.23975486]
Epoch: 4834 / 5000 batch_step: 420
w1: [50.80858929] w2: [-96.98348587] w3: [758.30568328] w4: [419.37597525] bias: [152.01965535]
Epoch: 4835 / 5000 batch_step: 0
w1: [50.79245509] w2: [-96.99101364] w3: [758.29486437] w4: [419.37113165] bias: [151.95409953]
Epoch: 4835 / 5000 batch_step: 30
w1: [50.80158043] w2: [-96.99179765] w3: [758.30524831] w4: [419.37219935] bias: [151.87700661]
Epoch: 4835 / 5000 batch_step: 60
w1: [50.79531906] w2: [-97.00516637] w3: [758.30014909] w4: [419.36843945] bias: [151.74194189]
Epoch: 4835 / 5000 batch_step: 90
w1: [50.77698986] w2: [-97.00586873] w3: [758.29776325] w4: [419.36302889] bias: [151.88894164]
Epoch: 4835 / 5000 batch_step: 120
w1: [50.77615009] w2: [-97.01860919] w3: [758.29506875] w4: [419.36352025] bias: [151.96974081]
Epoch: 4835 / 5000 batch_step: 150
w1: [50.77942181] w2: [-97.01295569] w3: [758.30557535] w4: [419.3631744] bias: [151.96376347]
Epoch: 4835 / 5000 batch_step: 180
w1: [50.79138704] w2: [-97.01420271] w3: [758.30349391] w4: [419.35250732] bias: [151.8080118]
Epoch: 4835 / 5000 batch_step: 210
w1: [50.76543822] w2: [-97.00643348] w3: [758.30107075] w4: [419.35137976] bias: [151.94846448]
Epoch: 4835 / 5000 batch_step: 240
w1: [50.76261704] w2: [-97.00157423] w3: [758.32815514] w4: [419.36144759] bias: [151.76350595]
Epoch: 4835 / 5000 batch_step: 270
w1: [50.78387006] w2: [-97.00670182] w3: [758.32704566] w4: [419.37137917] bias: [151.88133305]
Epoch: 4835 / 5000 batch_step: 300
w1: [50.79369034] w2: [-96.99824851] w3: [758.31361319] w4: [419.37201977] bias: [151.87131819]
Epoch: 4835 / 5000 batch_step: 330
w1: [50.79498366] w2: [-96.99870103] w3: [758.32408705] w4: [419.36451287] bias: [152.08182342]
Epoch: 4835 / 5000 batch_step: 360
w1: [50.79189812] w2: [-96.98980437] w3: [758.31742696] w4: [419.36142379] bias: [152.08770174]
Epoch: 4835 / 5000 batch_step: 390
w1: [50.8050473] w2: [-96.98666504] w3: [758.31671958] w4: [419.37841234] bias: [152.23975448]
Epoch: 4835 / 5000 batch_step: 420
w1: [50.80020806] w2: [-96.99144016] w3: [758.32387742] w4: [419.37681305] bias: [152.01965839]
Epoch: 4836 / 5000 batch_step: 0
w1: [50.78407424] w2: [-96.99896763] w3: [758.3130582] w4: [419.37196962] bias: [151.95410135]
Epoch: 4836 / 5000 batch_step: 30
w1: [50.79319996] w2: [-96.99975145] w3: [758.32344149] w4: [419.37303716] bias: [151.8770099]
Epoch: 4836 / 5000 batch_step: 60
w1: [50.78693877] w2: [-97.01311975] w3: [758.31834188] w4: [419.36927698] bias: [151.74195129]
Epoch: 4836 / 5000 batch_step: 90
w1: [50.76860987] w2: [-97.0138216] w3: [758.31595534] w4: [419.36386644] bias: [151.88894808]
Epoch: 4836 / 5000 batch_step: 120
w1: [50.76777044] w2: [-97.02656166] w3: [758.31325973] w4: [419.36435741] bias: [151.96973622]
Epoch: 4836 / 5000 batch_step: 150
w1: [50.77104219] w2: [-97.02090799] w3: [758.32376566] w4: [419.36401125] bias: [151.96375952]
Epoch: 4836 / 5000 batch_step: 180
w1: [50.78300789] w2: [-97.02215464] w3: [758.32168372] w4: [419.35334423] bias: [151.8080127]
Epoch: 4836 / 5000 batch_step: 210
w1: [50.75705923] w2: [-97.01438526] w3: [758.31926011] w4: [419.35221663] bias: [151.94846814]
Epoch: 4836 / 5000 batch_step: 240
w1: [50.75423825] w2: [-97.00952581] w3: [758.34634311] w4: [419.36228408] bias: [151.76350661]
Epoch: 4836 / 5000 batch_step: 270
w1: [50.77549177] w2: [-97.01465305] w3: [758.34523299] w4: [419.37221548] bias: [151.88134012]
Epoch: 4836 / 5000 batch_step: 300
w1: [50.78531215] w2: [-97.00619908] w3: [758.33179978] w4: [419.37285617] bias: [151.87132258]
Epoch: 4836 / 5000 batch_step: 330
w1: [50.7866058] w2: [-97.00665117] w3: [758.34227292] w4: [419.36534882] bias: [152.08183067]
Epoch: 4836 / 5000 batch_step: 360
w1: [50.78352049] w2: [-96.99775422] w3: [758.33561177] w4: [419.36225978] bias: [152.08770829]
Epoch: 4836 / 5000 batch_step: 390
w1: [50.79666994] w2: [-96.99461441] w3: [758.33490331] w4: [419.37924804] bias: [152.23975411]
Epoch: 4836 / 5000 batch_step: 420
w1: [50.79183099] w2: [-96.99938933] w3: [758.34206056] w4: [419.37764861] bias: [152.01966143]
Epoch: 4837 / 5000 batch_step: 0
w1: [50.77569755] w2: [-97.00691648] w3: [758.33124103] w4: [419.37280534] bias: [151.95410316]
Epoch: 4837 / 5000 batch_step: 30
w1: [50.78482364] w2: [-97.00770013] w3: [758.34162366] w4: [419.37387273] bias: [151.87701319]
Epoch: 4837 / 5000 batch_step: 60
w1: [50.77856263] w2: [-97.02106801] w3: [758.33652366] w4: [419.37011227] bias: [151.7419607]
Epoch: 4837 / 5000 batch_step: 90
w1: [50.76023403] w2: [-97.02176935] w3: [758.33413642] w4: [419.36470174] bias: [151.88895451]
Epoch: 4837 / 5000 batch_step: 120
w1: [50.75939494] w2: [-97.03450901] w3: [758.3314397] w4: [419.36519233] bias: [151.96973164]
Epoch: 4837 / 5000 batch_step: 150
w1: [50.76266672] w2: [-97.02885517] w3: [758.34194496] w4: [419.36484585] bias: [151.96375557]
Epoch: 4837 / 5000 batch_step: 180
w1: [50.77463289] w2: [-97.03010144] w3: [758.33986252] w4: [419.35417891] bias: [151.8080136]
Epoch: 4837 / 5000 batch_step: 210
w1: [50.74868439] w2: [-97.02233192] w3: [758.33743845] w4: [419.35305126] bias: [151.94847179]
Epoch: 4837 / 5000 batch_step: 240
w1: [50.74586362] w2: [-97.01747226] w3: [758.36452007] w4: [419.36311833] bias: [151.76350726]
Epoch: 4837 / 5000 batch_step: 270
w1: [50.76711763] w2: [-97.02259915] w3: [758.36340932] w4: [419.37304956] bias: [151.88134719]
Epoch: 4837 / 5000 batch_step: 300
w1: [50.77693811] w2: [-97.01414453] w3: [758.34997536] w4: [419.37369032] bias: [151.87132696]
Epoch: 4837 / 5000 batch_step: 330
w1: [50.77823209] w2: [-97.01459618] w3: [758.36044778] w4: [419.36618253] bias: [152.08183792]
Epoch: 4837 / 5000 batch_step: 360
w1: [50.77514702] w2: [-97.00569896] w3: [758.35378558] w4: [419.36309353] bias: [152.08771484]
Epoch: 4837 / 5000 batch_step: 390
w1: [50.78829673] w2: [-97.00255866] w3: [758.35307603] w4: [419.38008151] bias: [152.23975373]
Epoch: 4837 / 5000 batch_step: 420
w1: [50.78345807] w2: [-97.00733337] w3: [758.36023268] w4: [419.37848194] bias: [152.01966447]
Epoch: 4838 / 5000 batch_step: 0
w1: [50.76732501] w2: [-97.01486022] w3: [758.34941285] w4: [419.37363883] bias: [151.95410497]
Epoch: 4838 / 5000 batch_step: 30
w1: [50.77645148] w2: [-97.01564368] w3: [758.35979483] w4: [419.37470606] bias: [151.87701647]
Epoch: 4838 / 5000 batch_step: 60
w1: [50.77019064] w2: [-97.02901114] w3: [758.35469443] w4: [419.37094532] bias: [151.74197009]
Epoch: 4838 / 5000 batch_step: 90
w1: [50.75186235] w2: [-97.02971198] w3: [758.3523065] w4: [419.36553481] bias: [151.88896094]
Epoch: 4838 / 5000 batch_step: 120
w1: [50.7510236] w2: [-97.04245124] w3: [758.34960868] w4: [419.36602502] bias: [151.96972705]
Epoch: 4838 / 5000 batch_step: 150
w1: [50.7542954] w2: [-97.03679723] w3: [758.36011326] w4: [419.36567822] bias: [151.96375162]
Epoch: 4838 / 5000 batch_step: 180
w1: [50.76626204] w2: [-97.03804313] w3: [758.35803032] w4: [419.35501135] bias: [151.80801449]
Epoch: 4838 / 5000 batch_step: 210
w1: [50.7403137] w2: [-97.03027345] w3: [758.3556058] w4: [419.35388365] bias: [151.94847544]
Epoch: 4838 / 5000 batch_step: 240
w1: [50.73749315] w2: [-97.02541359] w3: [758.38268604] w4: [419.36395034] bias: [151.76350792]
Epoch: 4838 / 5000 batch_step: 270
w1: [50.75874765] w2: [-97.03054014] w3: [758.38157464] w4: [419.37388139] bias: [151.88135426]
Epoch: 4838 / 5000 batch_step: 300
w1: [50.76856823] w2: [-97.02208485] w3: [758.36813995] w4: [419.37452225] bias: [151.87133134]
Epoch: 4838 / 5000 batch_step: 330
w1: [50.76986253] w2: [-97.02253608] w3: [758.37861165] w4: [419.36701401] bias: [152.08184517]
Epoch: 4838 / 5000 batch_step: 360
w1: [50.7667777] w2: [-97.01363857] w3: [758.37194839] w4: [419.36392504] bias: [152.08772139]
Epoch: 4838 / 5000 batch_step: 390
w1: [50.77992767] w2: [-97.01049778] w3: [758.37123776] w4: [419.38091274] bias: [152.23975336]
Epoch: 4838 / 5000 batch_step: 420
w1: [50.7750893] w2: [-97.0152723] w3: [758.37839382] w4: [419.37931303] bias: [152.01966751]
Epoch: 4839 / 5000 batch_step: 0
w1: [50.75895662] w2: [-97.02279884] w3: [758.36757368] w4: [419.37447009] bias: [151.95410678]
Epoch: 4839 / 5000 batch_step: 30
w1: [50.76808347] w2: [-97.02358212] w3: [758.37795501] w4: [419.37553716] bias: [151.87701976]
Epoch: 4839 / 5000 batch_step: 60
w1: [50.7618228] w2: [-97.03694915] w3: [758.37285422] w4: [419.37177614] bias: [151.74197948]
Epoch: 4839 / 5000 batch_step: 90
w1: [50.74349482] w2: [-97.03764949] w3: [758.37046558] w4: [419.36636565] bias: [151.88896736]
Epoch: 4839 / 5000 batch_step: 120
w1: [50.7426564] w2: [-97.05038835] w3: [758.36776666] w4: [419.36685547] bias: [151.96972246]
Epoch: 4839 / 5000 batch_step: 150
w1: [50.74592823] w2: [-97.04473417] w3: [758.37827057] w4: [419.36650835] bias: [151.96374767]
Epoch: 4839 / 5000 batch_step: 180
w1: [50.75789535] w2: [-97.0459797] w3: [758.37618713] w4: [419.35584156] bias: [151.80801539]
Epoch: 4839 / 5000 batch_step: 210
w1: [50.73194716] w2: [-97.03820987] w3: [758.37376215] w4: [419.35471381] bias: [151.94847909]
Epoch: 4839 / 5000 batch_step: 240
w1: [50.72912682] w2: [-97.03334981] w3: [758.40084101] w4: [419.36478012] bias: [151.76350857]
Epoch: 4839 / 5000 batch_step: 270
w1: [50.75038181] w2: [-97.038476] w3: [758.39972898] w4: [419.374711] bias: [151.88136132]
Epoch: 4839 / 5000 batch_step: 300
w1: [50.7602025] w2: [-97.03002006] w3: [758.38629355] w4: [419.37535193] bias: [151.87133571]
Epoch: 4839 / 5000 batch_step: 330
w1: [50.76149713] w2: [-97.03047085] w3: [758.39676452] w4: [419.36784325] bias: [152.08185241]
Epoch: 4839 / 5000 batch_step: 360
w1: [50.75841253] w2: [-97.02157307] w3: [758.39010021] w4: [419.36475432] bias: [152.08772793]
Epoch: 4839 / 5000 batch_step: 390
w1: [50.77156276] w2: [-97.0184318] w3: [758.3893885] w4: [419.38174174] bias: [152.23975299]
Epoch: 4839 / 5000 batch_step: 420
w1: [50.76672468] w2: [-97.02320611] w3: [758.39654396] w4: [419.38014188] bias: [152.01967055]
Epoch: 4840 / 5000 batch_step: 0
w1: [50.75059238] w2: [-97.03073234] w3: [758.38572352] w4: [419.37529911] bias: [151.95410859]
Epoch: 4840 / 5000 batch_step: 30
w1: [50.75971961] w2: [-97.03151543] w3: [758.39610419] w4: [419.37636603] bias: [151.87702304]
Epoch: 4840 / 5000 batch_step: 60
w1: [50.75345912] w2: [-97.04488205] w3: [758.39100301] w4: [419.37260473] bias: [151.74198886]
Epoch: 4840 / 5000 batch_step: 90
w1: [50.73513144] w2: [-97.04558189] w3: [758.38861368] w4: [419.36719426] bias: [151.88897378]
Epoch: 4840 / 5000 batch_step: 120
w1: [50.73429336] w2: [-97.05832035] w3: [758.38591365] w4: [419.36768369] bias: [151.96971788]
Epoch: 4840 / 5000 batch_step: 150
w1: [50.73756521] w2: [-97.05266599] w3: [758.39641689] w4: [419.36733626] bias: [151.96374373]
Epoch: 4840 / 5000 batch_step: 180
w1: [50.7495328] w2: [-97.05391115] w3: [758.39433295] w4: [419.35666953] bias: [151.80801628]
Epoch: 4840 / 5000 batch_step: 210
w1: [50.72358478] w2: [-97.04614117] w3: [758.39190752] w4: [419.35554174] bias: [151.94848273]
Epoch: 4840 / 5000 batch_step: 240
w1: [50.72076464] w2: [-97.04128091] w3: [758.418985] w4: [419.36560767] bias: [151.76350923]
Epoch: 4840 / 5000 batch_step: 270
w1: [50.74202013] w2: [-97.04640676] w3: [758.41787233] w4: [419.37553837] bias: [151.88136837]
Epoch: 4840 / 5000 batch_step: 300
w1: [50.75184091] w2: [-97.03795016] w3: [758.40443616] w4: [419.37617939] bias: [151.87134009]
Epoch: 4840 / 5000 batch_step: 330
w1: [50.75313587] w2: [-97.03840052] w3: [758.41490641] w4: [419.36867027] bias: [152.08185965]
Epoch: 4840 / 5000 batch_step: 360
w1: [50.75005151] w2: [-97.02950246] w3: [758.40824105] w4: [419.36558138] bias: [152.08773447]
Epoch: 4840 / 5000 batch_step: 390
w1: [50.763202] w2: [-97.0263607] w3: [758.40752825] w4: [419.38256852] bias: [152.23975262]
Epoch: 4840 / 5000 batch_step: 420
w1: [50.7583642] w2: [-97.0311348] w3: [758.41468313] w4: [419.38096851] bias: [152.01967358]
Epoch: 4841 / 5000 batch_step: 0
w1: [50.74223228] w2: [-97.03866073] w3: [758.40386238] w4: [419.3761259] bias: [151.9541104]
Epoch: 4841 / 5000 batch_step: 30
w1: [50.75135989] w2: [-97.03944364] w3: [758.4142424] w4: [419.37719267] bias: [151.87702631]
Epoch: 4841 / 5000 batch_step: 60
w1: [50.74509958] w2: [-97.05280984] w3: [758.40914083] w4: [419.37343109] bias: [151.74199823]
Epoch: 4841 / 5000 batch_step: 90
w1: [50.72677221] w2: [-97.05350917] w3: [758.40675079] w4: [419.36802063] bias: [151.88898019]
Epoch: 4841 / 5000 batch_step: 120
w1: [50.72593446] w2: [-97.06624724] w3: [758.40404966] w4: [419.36850969] bias: [151.9697133]
Epoch: 4841 / 5000 batch_step: 150
w1: [50.72920634] w2: [-97.06059271] w3: [758.41455223] w4: [419.36816194] bias: [151.96373978]
Epoch: 4841 / 5000 batch_step: 180
w1: [50.7411744] w2: [-97.06183749] w3: [758.41246779] w4: [419.35749528] bias: [151.80801717]
Epoch: 4841 / 5000 batch_step: 210
w1: [50.71522654] w2: [-97.05406736] w3: [758.41004191] w4: [419.35636744] bias: [151.94848638]
Epoch: 4841 / 5000 batch_step: 240
w1: [50.71240661] w2: [-97.0492069] w3: [758.43711801] w4: [419.36643299] bias: [151.76350988]
Epoch: 4841 / 5000 batch_step: 270
w1: [50.73366259] w2: [-97.0543324] w3: [758.4360047] w4: [419.37636352] bias: [151.88137542]
Epoch: 4841 / 5000 batch_step: 300
w1: [50.74348348] w2: [-97.04587514] w3: [758.42256779] w4: [419.37700463] bias: [151.87134446]
Epoch: 4841 / 5000 batch_step: 330
w1: [50.74477876] w2: [-97.04632507] w3: [758.43303733] w4: [419.36949506] bias: [152.08186689]
Epoch: 4841 / 5000 batch_step: 360
w1: [50.74169464] w2: [-97.03742674] w3: [758.42637091] w4: [419.3664062] bias: [152.08774101]
Epoch: 4841 / 5000 batch_step: 390
w1: [50.75484539] w2: [-97.03428449] w3: [758.42565703] w4: [419.38339306] bias: [152.23975225]
Epoch: 4841 / 5000 batch_step: 420
w1: [50.75000788] w2: [-97.03905839] w3: [758.43281132] w4: [419.38179291] bias: [152.01967662]
Epoch: 4842 / 5000 batch_step: 0
w1: [50.73387634] w2: [-97.04658401] w3: [758.42199026] w4: [419.37695047] bias: [151.95411221]
Epoch: 4842 / 5000 batch_step: 30
w1: [50.74300432] w2: [-97.04736674] w3: [758.43236963] w4: [419.37801709] bias: [151.87702959]
Epoch: 4842 / 5000 batch_step: 60
w1: [50.73674419] w2: [-97.06073252] w3: [758.42726767] w4: [419.37425522] bias: [151.7420076]
Epoch: 4842 / 5000 batch_step: 90
w1: [50.71841712] w2: [-97.06143134] w3: [758.42487693] w4: [419.36884478] bias: [151.88898659]
Epoch: 4842 / 5000 batch_step: 120
w1: [50.71757971] w2: [-97.07416901] w3: [758.42217471] w4: [419.36933345] bias: [151.96970871]
Epoch: 4842 / 5000 batch_step: 150
w1: [50.72085162] w2: [-97.06851431] w3: [758.4326766] w4: [419.36898539] bias: [151.96373584]
Epoch: 4842 / 5000 batch_step: 180
w1: [50.73282015] w2: [-97.06975872] w3: [758.43059167] w4: [419.35831881] bias: [151.80801806]
Epoch: 4842 / 5000 batch_step: 210
w1: [50.70687245] w2: [-97.06198844] w3: [758.42816532] w4: [419.35719091] bias: [151.94849002]
Epoch: 4842 / 5000 batch_step: 240
w1: [50.70405273] w2: [-97.05712779] w3: [758.45524005] w4: [419.36725609] bias: [151.76351053]
Epoch: 4842 / 5000 batch_step: 270
w1: [50.7253092] w2: [-97.06225293] w3: [758.45412611] w4: [419.37718645] bias: [151.88138247]
Epoch: 4842 / 5000 batch_step: 300
w1: [50.73513019] w2: [-97.05379502] w3: [758.44068846] w4: [419.37782764] bias: [151.87134883]
Epoch: 4842 / 5000 batch_step: 330
w1: [50.7364258] w2: [-97.05424452] w3: [758.45115728] w4: [419.37031762] bias: [152.08187412]
Epoch: 4842 / 5000 batch_step: 360
w1: [50.73334191] w2: [-97.0453459] w3: [758.4444898] w4: [419.3672288] bias: [152.08774754]
Epoch: 4842 / 5000 batch_step: 390
w1: [50.74649293] w2: [-97.04220317] w3: [758.44377484] w4: [419.38421538] bias: [152.23975188]
Epoch: 4842 / 5000 batch_step: 420
w1: [50.7416557] w2: [-97.04697687] w3: [758.45092854] w4: [419.38261509] bias: [152.01967965]
Epoch: 4843 / 5000 batch_step: 0
w1: [50.72552454] w2: [-97.05450219] w3: [758.44010718] w4: [419.37777281] bias: [151.95411402]
Epoch: 4843 / 5000 batch_step: 30
w1: [50.7346529] w2: [-97.05528472] w3: [758.4504859] w4: [419.37883928] bias: [151.87703286]
Epoch: 4843 / 5000 batch_step: 60
w1: [50.72839295] w2: [-97.06865009] w3: [758.44538354] w4: [419.37507713] bias: [151.74201696]
Epoch: 4843 / 5000 batch_step: 90
w1: [50.71006618] w2: [-97.06934841] w3: [758.44299211] w4: [419.36966671] bias: [151.888993]
Epoch: 4843 / 5000 batch_step: 120
w1: [50.70922911] w2: [-97.08208568] w3: [758.44028878] w4: [419.370155] bias: [151.96970413]
Epoch: 4843 / 5000 batch_step: 150
w1: [50.71250104] w2: [-97.07643081] w3: [758.45079] w4: [419.36980662] bias: [151.9637319]
Epoch: 4843 / 5000 batch_step: 180
w1: [50.72447004] w2: [-97.07767485] w3: [758.44870457] w4: [419.35914011] bias: [151.80801895]
Epoch: 4843 / 5000 batch_step: 210
w1: [50.6985225] w2: [-97.06990442] w3: [758.44627778] w4: [419.35801217] bias: [151.94849365]
Epoch: 4843 / 5000 batch_step: 240
w1: [50.69570299] w2: [-97.06504356] w3: [758.47335113] w4: [419.36807696] bias: [151.76351119]
Epoch: 4843 / 5000 batch_step: 270
w1: [50.71695995] w2: [-97.07016836] w3: [758.47223655] w4: [419.37800715] bias: [151.88138951]
Epoch: 4843 / 5000 batch_step: 300
w1: [50.72678104] w2: [-97.06170979] w3: [758.45879816] w4: [419.37864842] bias: [151.8713532]
Epoch: 4843 / 5000 batch_step: 330
w1: [50.72807698] w2: [-97.06215886] w3: [758.46926626] w4: [419.37113797] bias: [152.08188134]
Epoch: 4843 / 5000 batch_step: 360
w1: [50.72499333] w2: [-97.05325997] w3: [758.46259773] w4: [419.36804918] bias: [152.08775407]
Epoch: 4843 / 5000 batch_step: 390
w1: [50.7381446] w2: [-97.05011675] w3: [758.4618817] w4: [419.38503548] bias: [152.23975151]
Epoch: 4843 / 5000 batch_step: 420
w1: [50.73330767] w2: [-97.05489024] w3: [758.4690348] w4: [419.38343505] bias: [152.01968268]
Epoch: 4844 / 5000 batch_step: 0
w1: [50.71717688] w2: [-97.06241525] w3: [758.45821314] w4: [419.37859293] bias: [151.95411582]
Epoch: 4844 / 5000 batch_step: 30
w1: [50.72630562] w2: [-97.06319761] w3: [758.4685912] w4: [419.37965925] bias: [151.87703613]
Epoch: 4844 / 5000 batch_step: 60
w1: [50.72004584] w2: [-97.07656255] w3: [758.46348846] w4: [419.37589682] bias: [151.74202632]
Epoch: 4844 / 5000 batch_step: 90
w1: [50.70171938] w2: [-97.07726037] w3: [758.46109633] w4: [419.37048642] bias: [151.88899939]
Epoch: 4844 / 5000 batch_step: 120
w1: [50.70088264] w2: [-97.08999725] w3: [758.4583919] w4: [419.37097433] bias: [151.96969956]
Epoch: 4844 / 5000 batch_step: 150
w1: [50.7041546] w2: [-97.0843422] w3: [758.46889245] w4: [419.37062563] bias: [151.96372796]
Epoch: 4844 / 5000 batch_step: 180
w1: [50.71612407] w2: [-97.08558588] w3: [758.46680652] w4: [419.35995919] bias: [151.80801984]
Epoch: 4844 / 5000 batch_step: 210
w1: [50.69017669] w2: [-97.07781529] w3: [758.46437927] w4: [419.3588312] bias: [151.94849729]
Epoch: 4844 / 5000 batch_step: 240
w1: [50.6873574] w2: [-97.07295424] w3: [758.49145126] w4: [419.36889562] bias: [151.76351184]
Epoch: 4844 / 5000 batch_step: 270

In [ ]:
predicted = features[:, 0] * w1 + features[:, 1] * w2 + features[:, 2] * w3 + features[:, 3] * w4 + bias
diabetesDF['BATCH_PREDICTED_TARGET'] = predicted
diabetesDF.head(10)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target,BATCH_PREDICTED_TARGET
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0,205.062376
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0,106.087359
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0,182.718261
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0,127.796714
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0,138.151720
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346,97.0,112.687091
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357,138.0,102.181115
7,0.063504,0.050680,-0.001895,0.066629,0.090620,0.108914,0.022869,0.017703,-0.035816,0.003064,63.0,176.691185
8,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014960,0.011349,110.0,179.245970
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504,310.0,168.698749

# Mini BATCH GD를 keras로 수행
 - keras는 기본적으로 mini batch gd를 수행

In [ ]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

model = Sequential([
    # 단 하나의 units 설정.
    # input_shape는 2차원, 회귀이므로 activation은 설정하지 않음.
    Dense(1, input_shape=(4,), activation=None, kernel_initializer='zeros', bias_initializer='ones')
])
# Adam optimizer를 이용하고 loss 함수는 mse, 성능측정도 mse를 이용하여 학습 수행.
model.compile(optimizer=Adam(learning_rate=0.01), loss='mse', metrics=['mse'])

# keras는 반드시 batch GD를 적용함. batch_size가 none이면 32를 할당.
model.fit(features, diabetesDF['target'].values, batch_size=30, epochs=1000)

Epoch 1/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 28749.9102 - mse: 28749.9102
Epoch 2/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28703.8105 - mse: 28703.8105
Epoch 3/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28657.6973 - mse: 28657.6973
Epoch 4/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28612.2246 - mse: 28612.2246
Epoch 5/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28565.7227 - mse: 28565.7227
Epoch 6/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28520.4824 - mse: 28520.4824
Epoch 7/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28474.7754 - mse: 28474.7754
Epoch 8/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28428.8301 - mse: 28428.8301
Epoch 9/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28383.5156 - mse: 28383.5156
Epoch 10/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28338.4102 - mse: 28338.4102
Epoch 11/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28292.0664 - mse: 28292.0664
Epoch 12/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28247.7305 - mse: 28247.7305
Epoch 13/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28201.7461 - mse: 28201.7461
Epoch 14/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28156.6797 - mse: 28156.6797
Epoch 15/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28111.5547 - mse: 28111.5547
Epoch 16/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28066.6094 - mse: 28066.6094
Epoch 17/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28021.6719 - mse: 28021.6719
Epoch 18/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27976.5000 - mse: 27976.5000
Epoch 19/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27931.8535 - mse: 27931.8535
Epoch 20/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27887.0176 - mse: 27887.0176
Epoch 21/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27842.2598 - mse: 27842.2598
Epoch 22/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27797.4316 - mse: 27797.4316
Epoch 23/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27752.6055 - mse: 27752.6055
Epoch 24/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27708.4414 - mse: 27708.4414
Epoch 25/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27663.7773 - mse: 27663.7773
Epoch 26/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27619.2812 - mse: 27619.2812
Epoch 27/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27574.6582 - mse: 27574.6582
Epoch 28/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27530.2773 - mse: 27530.2773
Epoch 29/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27486.6816 - mse: 27486.6816
Epoch 30/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27441.6875 - mse: 27441.6875
Epoch 31/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27397.4258 - mse: 27397.4258
Epoch 32/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27353.6699 - mse: 27353.6699
Epoch 33/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27309.5234 - mse: 27309.5234
Epoch 34/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27265.2402 - mse: 27265.2402
Epoch 35/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27221.1758 - mse: 27221.1758
Epoch 36/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27177.8535 - mse: 27177.8535
Epoch 37/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27134.0918 - mse: 27134.0918
Epoch 38/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27089.7754 - mse: 27089.7754
Epoch 39/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27046.3438 - mse: 27046.3438
Epoch 40/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27002.3555 - mse: 27002.3555
Epoch 41/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26959.2324 - mse: 26959.2324
Epoch 42/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26916.1113 - mse: 26916.1113
Epoch 43/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26872.0176 - mse: 26872.0176
Epoch 44/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26829.0000 - mse: 26829.0000
Epoch 45/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26785.9824 - mse: 26785.9824
Epoch 46/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26742.2383 - mse: 26742.2383
Epoch 47/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26699.3125 - mse: 26699.3125
Epoch 48/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26655.7754 - mse: 26655.7754
Epoch 49/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26613.0098 - mse: 26613.0098
Epoch 50/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26569.9375 - mse: 26569.9375
Epoch 51/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26527.2715 - mse: 26527.2715
Epoch 52/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26484.1758 - mse: 26484.1758
Epoch 53/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26441.5254 - mse: 26441.5254
Epoch 54/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26398.4746 - mse: 26398.4746
Epoch 55/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26356.1660 - mse: 26356.1660
Epoch 56/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26313.4277 - mse: 26313.4277
Epoch 57/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26271.1367 - mse: 26271.1367
Epoch 58/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26227.8340 - mse: 26227.8340
Epoch 59/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26185.5117 - mse: 26185.5117
Epoch 60/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26143.0293 - mse: 26143.0293
Epoch 61/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26101.1230 - mse: 26101.1230
Epoch 62/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26058.4043 - mse: 26058.4043
Epoch 63/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26016.3672 - mse: 26016.3672
Epoch 64/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25974.0469 - mse: 25974.0469
Epoch 65/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25932.0469 - mse: 25932.0469
Epoch 66/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25890.1699 - mse: 25890.1699
Epoch 67/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25847.8379 - mse: 25847.8379
Epoch 68/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25805.9609 - mse: 25805.9609
Epoch 69/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25764.1367 - mse: 25764.1367
Epoch 70/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25722.7715 - mse: 25722.7715
Epoch 71/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25680.8262 - mse: 25680.8262
Epoch 72/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25638.4844 - mse: 25638.4844
Epoch 73/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25597.4277 - mse: 25597.4277
Epoch 74/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25555.2520 - mse: 25555.2520
Epoch 75/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25514.0684 - mse: 25514.0684
Epoch 76/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25472.3613 - mse: 25472.3613
Epoch 77/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25431.0957 - mse: 25431.0957
Epoch 78/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25389.4160 - mse: 25389.4160
Epoch 79/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25347.8828 - mse: 25347.8828
Epoch 80/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25307.3828 - mse: 25307.3828
Epoch 81/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25265.7402 - mse: 25265.7402
Epoch 82/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25224.8613 - mse: 25224.8613
Epoch 83/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25183.5312 - mse: 25183.5312
Epoch 84/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25142.4414 - mse: 25142.4414
Epoch 85/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25101.7383 - mse: 25101.7383
Epoch 86/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25060.8242 - mse: 25060.8242
Epoch 87/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25020.0703 - mse: 25020.0703
Epoch 88/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24979.1035 - mse: 24979.1035
Epoch 89/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24938.5234 - mse: 24938.5234
Epoch 90/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24897.6523 - mse: 24897.6523
Epoch 91/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24857.3438 - mse: 24857.3438
Epoch 92/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24816.6953 - mse: 24816.6953
Epoch 93/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24776.0410 - mse: 24776.0410
Epoch 94/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24735.4688 - mse: 24735.4688
Epoch 95/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24695.2617 - mse: 24695.2617
Epoch 96/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24654.5625 - mse: 24654.5625
Epoch 97/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24614.9023 - mse: 24614.9023
Epoch 98/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24573.7734 - mse: 24573.7734
Epoch 99/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24534.1484 - mse: 24534.1484
Epoch 100/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24493.5332 - mse: 24493.5332
Epoch 101/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24453.4980 - mse: 24453.4980
Epoch 102/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24413.6191 - mse: 24413.6191
Epoch 103/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24373.2559 - mse: 24373.2559
Epoch 104/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24333.3262 - mse: 24333.3262
Epoch 105/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24293.3242 - mse: 24293.3242
Epoch 106/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24253.6035 - mse: 24253.6035
Epoch 107/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24213.5625 - mse: 24213.5625
Epoch 108/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24174.1660 - mse: 24174.1660
Epoch 109/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24134.3887 - mse: 24134.3887
Epoch 110/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24094.6250 - mse: 24094.6250
Epoch 111/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24055.1680 - mse: 24055.1680
Epoch 112/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24015.5801 - mse: 24015.5801
Epoch 113/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23976.6426 - mse: 23976.6426
Epoch 114/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23936.8770 - mse: 23936.8770
Epoch 115/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23897.2246 - mse: 23897.2246
Epoch 116/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23858.0723 - mse: 23858.0723
Epoch 117/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23818.9805 - mse: 23818.9805
Epoch 118/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23779.8438 - mse: 23779.8438
Epoch 119/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23740.3711 - mse: 23740.3711
Epoch 120/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23701.4844 - mse: 23701.4844
Epoch 121/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23662.5137 - mse: 23662.5137
Epoch 122/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23623.4746 - mse: 23623.4746
Epoch 123/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23584.4102 - mse: 23584.4102
Epoch 124/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23545.5547 - mse: 23545.5547
Epoch 125/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23506.5195 - mse: 23506.5195
Epoch 126/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23467.8770 - mse: 23467.8770
Epoch 127/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23428.7715 - mse: 23428.7715
Epoch 128/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23390.2559 - mse: 23390.2559
Epoch 129/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23351.3477 - mse: 23351.3477
Epoch 130/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23312.7852 - mse: 23312.7852
Epoch 131/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23274.1797 - mse: 23274.1797
Epoch 132/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23235.6621 - mse: 23235.6621
Epoch 133/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23196.7109 - mse: 23196.7109
Epoch 134/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23158.5586 - mse: 23158.5586
Epoch 135/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23120.4297 - mse: 23120.4297
Epoch 136/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23081.3965 - mse: 23081.3965
Epoch 137/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23043.6895 - mse: 23043.6895
Epoch 138/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23004.9434 - mse: 23004.9434
Epoch 139/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22967.0293 - mse: 22967.0293
Epoch 140/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22928.9238 - mse: 22928.9238
Epoch 141/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22890.8164 - mse: 22890.8164
Epoch 142/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22853.1621 - mse: 22853.1621
Epoch 143/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22814.7852 - mse: 22814.7852
Epoch 144/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22777.3320 - mse: 22777.3320
Epoch 145/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22739.0156 - mse: 22739.0156
Epoch 146/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22701.1270 - mse: 22701.1270
Epoch 147/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22663.6113 - mse: 22663.6113
Epoch 148/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22625.9043 - mse: 22625.9043
Epoch 149/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22588.5723 - mse: 22588.5723
Epoch 150/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22550.2266 - mse: 22550.2266
Epoch 151/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22512.9668 - mse: 22512.9668
Epoch 152/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22475.2969 - mse: 22475.2969
Epoch 153/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22437.8379 - mse: 22437.8379
Epoch 154/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22400.4688 - mse: 22400.4688
Epoch 155/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22362.7910 - mse: 22362.7910
Epoch 156/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22325.4590 - mse: 22325.4590
Epoch 157/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22288.4473 - mse: 22288.4473
Epoch 158/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22251.2227 - mse: 22251.2227
Epoch 159/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22213.5254 - mse: 22213.5254
Epoch 160/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22177.1426 - mse: 22177.1426
Epoch 161/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22139.5488 - mse: 22139.5488
Epoch 162/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22102.8906 - mse: 22102.8906
Epoch 163/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22065.8242 - mse: 22065.8242
Epoch 164/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22028.9941 - mse: 22028.9941
Epoch 165/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21992.0410 - mse: 21992.0410
Epoch 166/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21955.3301 - mse: 21955.3301
Epoch 167/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21918.8555 - mse: 21918.8555
Epoch 168/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21881.6289 - mse: 21881.6289
Epoch 169/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21845.5879 - mse: 21845.5879
Epoch 170/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21809.0176 - mse: 21809.0176
Epoch 171/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21772.3809 - mse: 21772.3809
Epoch 172/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21735.4551 - mse: 21735.4551
Epoch 173/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21699.7754 - mse: 21699.7754
Epoch 174/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21662.6543 - mse: 21662.6543
Epoch 175/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21627.0469 - mse: 21627.0469
Epoch 176/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21589.9473 - mse: 21589.9473
Epoch 177/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21553.9961 - mse: 21553.9961
Epoch 178/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21517.9668 - mse: 21517.9668
Epoch 179/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21481.4473 - mse: 21481.4473
Epoch 180/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21445.7461 - mse: 21445.7461
Epoch 181/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21409.4297 - mse: 21409.4297
Epoch 182/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21373.0410 - mse: 21373.0410
Epoch 183/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21337.5000 - mse: 21337.5000
Epoch 184/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21301.4297 - mse: 21301.4297
Epoch 185/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21265.4980 - mse: 21265.4980
Epoch 186/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21229.6895 - mse: 21229.6895
Epoch 187/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21193.9238 - mse: 21193.9238
Epoch 188/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21158.0234 - mse: 21158.0234
Epoch 189/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21122.6523 - mse: 21122.6523
Epoch 190/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21087.0586 - mse: 21087.0586
Epoch 191/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21051.4824 - mse: 21051.4824
Epoch 192/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21015.7988 - mse: 21015.7988
Epoch 193/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20980.3203 - mse: 20980.3203
Epoch 194/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20945.2266 - mse: 20945.2266
Epoch 195/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20909.6680 - mse: 20909.6680
Epoch 196/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20874.2031 - mse: 20874.2031
Epoch 197/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20838.7715 - mse: 20838.7715
Epoch 198/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20803.4883 - mse: 20803.4883
Epoch 199/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20768.2695 - mse: 20768.2695
Epoch 200/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20732.9297 - mse: 20732.9297
Epoch 201/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20697.8301 - mse: 20697.8301
Epoch 202/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20662.5137 - mse: 20662.5137
Epoch 203/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20627.5273 - mse: 20627.5273
Epoch 204/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20592.1133 - mse: 20592.1133
Epoch 205/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20557.5391 - mse: 20557.5391
Epoch 206/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20522.6973 - mse: 20522.6973
Epoch 207/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20487.3457 - mse: 20487.3457
Epoch 208/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20452.9531 - mse: 20452.9531
Epoch 209/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20418.0762 - mse: 20418.0762
Epoch 210/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20382.9160 - mse: 20382.9160
Epoch 211/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20348.5020 - mse: 20348.5020
Epoch 212/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20313.6191 - mse: 20313.6191
Epoch 213/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20279.1309 - mse: 20279.1309
Epoch 214/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20244.9414 - mse: 20244.9414
Epoch 215/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20209.8965 - mse: 20209.8965
Epoch 216/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20175.5801 - mse: 20175.5801
Epoch 217/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20141.5059 - mse: 20141.5059
Epoch 218/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20106.7266 - mse: 20106.7266
Epoch 219/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20072.5469 - mse: 20072.5469
Epoch 220/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20038.1113 - mse: 20038.1113
Epoch 221/1000

In [ ]:
predicted = model.predict(features)
diabetesDF['KERAS_BATCH_PREDICTED_TARGET'] = predicted
diabetesDF.head(10)

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target,BATCH_PREDICTED_TARGET,KERAS_BATCH_PREDICTED_TARGET
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0,205.062376,145.100998
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0,106.087359,121.140495
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0,182.718261,143.085831
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0,127.796714,118.709915
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0,138.151720,129.221313
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346,97.0,112.687091,116.782059
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357,138.0,102.181115,120.875191
7,0.063504,0.050680,-0.001895,0.066629,0.090620,0.108914,0.022869,0.017703,-0.035816,0.003064,63.0,176.691185,144.124130
8,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014960,0.011349,110.0,179.245970,138.100143
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504,310.0,168.698749,126.832031